# Generated by Django 5.2.17 on 2026-09-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('registrar_hallazgo', 'Registrar hallazgos propios'), ('validar_hallazgo', 'Validar hallazgos de procesos asignados'), ('gestionar_tratamiento', 'Gestionar tratamiento de procesos asignados'), ('evaluar_eficacia', 'Evaluar eficacia de procesos asignados'), ('cerrar_hallazgo', 'Dar visto bueno administrativo y cerrar hallazgos'), ('ver_todos_hallazgos', 'Consultar todos los hallazgos'), ('administrar_plataforma', 'Administrar plataforma y catálogos')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
