# Generated by Django 5.2.17 on 2026-09-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_options'),
        ('hallazgos', '0015_eliminar_tipos_compatibilidad'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        ],
    )]
