# Generated by Django 5.2.17 on 2026-10-06 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SINCRONIZAR_ROLES = r"""
INSERT INTO usuario_rol (usuario_id, rol)
SELECT u.id, roles.rol
  FROM usuario u
 CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(u.roles, '[]'::jsonb)) AS roles(rol)
 WHERE roles.rol IN ('USUARIO', 'VALIDADOR', 'ADMINISTRADOR')
ON CONFLICT (usuario_id, rol) DO NOTHING;

CREATE OR REPLACE FUNCTION portal_sincronizar_usuario_roles()
RETURNS trigger AS $$
BEGIN
    DELETE FROM usuario_rol WHERE usuario_id = NEW.id;
    INSERT INTO usuario_rol (usuario_id, rol)
    SELECT NEW.id, roles.rol
      FROM jsonb_array_elements_text(COALESCE(NEW.roles, '[]'::jsonb)) AS roles(rol)
     WHERE roles.rol IN ('USUARIO', 'VALIDADOR', 'ADMINISTRADOR')
    ON CONFLICT (usuario_id, rol) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER usuario_roles_insertar
AFTER INSERT ON usuario
FOR EACH ROW EXECUTE FUNCTION portal_sincronizar_usuario_roles();

CREATE TRIGGER usuario_roles_actualizar
AFTER UPDATE OF roles ON usuario
FOR EACH ROW EXECUTE FUNCTION portal_sincronizar_usuario_roles();
"""

REVERTIR_ROLES = r"""
DROP TRIGGER IF EXISTS usuario_roles_insertar ON usuario;
DROP TRIGGER IF EXISTS usuario_roles_actualizar ON usuario;
DROP FUNCTION IF EXISTS portal_sincronizar_usuario_roles();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_direccion_usuario_gerencia_usuario_jefe'),
        ('hallazgos', '0020_snapshot_urgencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('VALIDADOR', 'Validador'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_rol',
                'ordering': ['usuario_id', 'rol'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol'), name='usuario_rol_unico')],
            },
        ),
        migrations.RunSQL(SINCRONIZAR_ROLES, REVERTIR_ROLES),
    ]
