# Generated by Django 5.2.17 on 2026-10-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuariorol'),
        ('catalogos', '0010_remove_catalogo_catalogo_clase_valor_unico_and_more'),
        ('hallazgos', '0023_remove_correlativosac_sac_anio_ambito_unico_and_more'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='tbl_usuario_nc',
        ),
        migrations.AlterModelTable(
            name='usuariorol',
            table='tbl_usuario_rol_nc',
        ),
        migrations.RunSQL(
            sql="ALTER TABLE django_session RENAME TO tbl_django_session_nc;",
            reverse_sql="ALTER TABLE tbl_django_session_nc RENAME TO django_session;",
        ),
        migrations.RunSQL(
            sql=r"""
            CREATE OR REPLACE FUNCTION portal_sincronizar_usuario_roles()
            RETURNS trigger AS $$
            BEGIN
                DELETE FROM tbl_usuario_rol_nc WHERE usuario_id = NEW.id;
                INSERT INTO tbl_usuario_rol_nc (usuario_id, rol)
                SELECT NEW.id, roles.rol
                  FROM jsonb_array_elements_text(COALESCE(NEW.roles, '[]'::jsonb)) AS roles(rol)
                 WHERE roles.rol IN ('USUARIO', 'VALIDADOR', 'ADMINISTRADOR')
                ON CONFLICT (usuario_id, rol) DO NOTHING;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql=r"""
            CREATE OR REPLACE FUNCTION portal_sincronizar_usuario_roles()
            RETURNS trigger AS $$
            BEGIN
                DELETE FROM usuario_rol WHERE usuario_id = NEW.id;
                INSERT INTO usuario_rol (usuario_id, rol)
                SELECT NEW.id, roles.rol
                  FROM jsonb_array_elements_text(COALESCE(NEW.roles, '[]'::jsonb)) AS roles(rol)
                 WHERE roles.rol IN ('USUARIO', 'VALIDADOR', 'ADMINISTRADOR')
                ON CONFLICT (usuario_id, rol) DO NOTHING;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
        ),
    ]
