PROMPT [1/9] Creacion de 24 tablas, PK, UK y CHECK

CREATE TABLE tbl_usuario_nc (
    id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                              (START WITH 1 INCREMENT BY 1 CACHE 100),
    password              NVARCHAR2(128) NOT NULL,
    last_login            TIMESTAMP(6),
    is_superuser          NUMBER(1) DEFAULT 0 NOT NULL,
    username              NVARCHAR2(150) NOT NULL,
    first_name            NVARCHAR2(150),
    last_name             NVARCHAR2(150),
    email                 NVARCHAR2(254),
    is_staff              NUMBER(1) DEFAULT 0 NOT NULL,
    is_active             NUMBER(1) DEFAULT 1 NOT NULL,
    date_joined           TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    area                  NVARCHAR2(150),
    cargo                 NVARCHAR2(150),
    corporate_identifier  NVARCHAR2(255),
    roles                 NCLOB NOT NULL,
    direccion             NVARCHAR2(150),
    gerencia              NVARCHAR2(150),
    jefe_id               NUMBER(19),
    CONSTRAINT pk_usuario_nc PRIMARY KEY (id),
    CONSTRAINT uk_usuario_username_nc UNIQUE (username),
    CONSTRAINT uk_usuario_corp_nc UNIQUE (corporate_identifier),
    CONSTRAINT ck_usr_super_nc CHECK (is_superuser IN (0, 1)),
    CONSTRAINT ck_usr_staff_nc CHECK (is_staff IN (0, 1)),
    CONSTRAINT ck_usr_active_nc CHECK (is_active IN (0, 1)),
    CONSTRAINT ck_usr_roles_json_nc CHECK (roles IS JSON (STRICT))
);

CREATE TABLE tbl_usuario_rol_nc (
    id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                    (START WITH 1 INCREMENT BY 1 CACHE 100),
    rol         NVARCHAR2(20) NOT NULL,
    usuario_id  NUMBER(19) NOT NULL,
    CONSTRAINT pk_usuario_rol_nc PRIMARY KEY (id),
    CONSTRAINT uk_usuario_rol_nc UNIQUE (usuario_id, rol),
    CONSTRAINT ck_usuario_rol_nc CHECK
        (rol IN ('USUARIO', 'VALIDADOR', 'ADMINISTRADOR'))
);

CREATE TABLE tbl_catalogo_nc (
    id      NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                (START WITH 1 INCREMENT BY 1 CACHE 100),
    clase   NVARCHAR2(12) NOT NULL,
    codigo  NVARCHAR2(30) NOT NULL,
    nombre  NVARCHAR2(180) NOT NULL,
    activo  NUMBER(1) DEFAULT 1 NOT NULL,
    valor   NUMBER(5),
    orden   NUMBER(5) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_catalogo_nc PRIMARY KEY (id),
    CONSTRAINT uk_cat_clase_codigo_nc UNIQUE (clase, codigo),
    CONSTRAINT uk_cat_clase_valor_nc UNIQUE (clase, valor),
    CONSTRAINT ck_cat_clase_nc CHECK
        (clase IN ('TIPO','FUENTE','IMPACTO','URGENCIA','PRIORIDAD','CATEGORIA')),
    CONSTRAINT ck_cat_activo_nc CHECK (activo IN (0, 1)),
    CONSTRAINT ck_cat_valor_nc CHECK (valor IS NULL OR valor >= 0),
    CONSTRAINT ck_cat_orden_nc CHECK (orden >= 0)
);

CREATE TABLE tbl_proceso_nc (
    id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                         (START WITH 1 INCREMENT BY 1 CACHE 100),
    nombre           NVARCHAR2(180) NOT NULL,
    activo           NUMBER(1) DEFAULT 1 NOT NULL,
    gerencia         NVARCHAR2(180),
    responsable_id   NUMBER(19),
    validadores_ids  NCLOB NOT NULL,
    CONSTRAINT pk_proceso_nc PRIMARY KEY (id),
    CONSTRAINT uk_proceso_nombre_nc UNIQUE (nombre),
    CONSTRAINT ck_proceso_activo_nc CHECK (activo IN (0, 1)),
    CONSTRAINT ck_proceso_json_nc CHECK (validadores_ids IS JSON (STRICT))
);

CREATE TABLE tbl_proceso_validador_nc (
    id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                    (START WITH 1 INCREMENT BY 1 CACHE 100),
    proceso_id  NUMBER(19) NOT NULL,
    usuario_id  NUMBER(19) NOT NULL,
    CONSTRAINT pk_proceso_validador_nc PRIMARY KEY (id),
    CONSTRAINT uk_proceso_validador_nc UNIQUE (proceso_id, usuario_id)
);

CREATE TABLE tbl_subproceso_nc (
    id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                    (START WITH 1 INCREMENT BY 1 CACHE 100),
    proceso_id  NUMBER(19) NOT NULL,
    nombre      NVARCHAR2(180) NOT NULL,
    activo      NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_subproceso_nc PRIMARY KEY (id),
    CONSTRAINT uk_subproceso_nombre_nc UNIQUE (proceso_id, nombre),
    CONSTRAINT ck_subproceso_activo_nc CHECK (activo IN (0, 1))
);

CREATE TABLE tbl_matriz_prioridad_nc (
    id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                      (START WITH 1 INCREMENT BY 1 CACHE 100),
    impacto_id    NUMBER(19) NOT NULL,
    urgencia_id   NUMBER(19) NOT NULL,
    prioridad_id  NUMBER(19) NOT NULL,
    activo        NUMBER(1) DEFAULT 1 NOT NULL,
    es_demo       NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_matriz_prioridad_nc PRIMARY KEY (id),
    CONSTRAINT uk_matriz_imp_urg_nc UNIQUE (impacto_id, urgencia_id),
    CONSTRAINT ck_matriz_activo_nc CHECK (activo IN (0, 1)),
    CONSTRAINT ck_matriz_demo_nc CHECK (es_demo IN (0, 1))
);

CREATE TABLE tbl_configuracion_impacto_nc (
    id                       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                                 (START WITH 1 INCREMENT BY 1 CACHE 100),
    predeterminada           NUMBER(1) DEFAULT 1 NOT NULL,
    clientes_bajo_desde      NUMBER(19) DEFAULT 0 NOT NULL,
    clientes_bajo_hasta      NUMBER(19) DEFAULT 90 NOT NULL,
    clientes_medio_desde     NUMBER(19) DEFAULT 91 NOT NULL,
    clientes_medio_hasta     NUMBER(19) DEFAULT 499 NOT NULL,
    clientes_alto_desde      NUMBER(19) DEFAULT 500 NOT NULL,
    tiempo_bajo_desde        NUMBER(10) DEFAULT 0 NOT NULL,
    tiempo_bajo_hasta        NUMBER(10) DEFAULT 29 NOT NULL,
    tiempo_medio_desde       NUMBER(10) DEFAULT 30 NOT NULL,
    tiempo_medio_hasta       NUMBER(10) DEFAULT 120 NOT NULL,
    tiempo_alto_desde        NUMBER(10) DEFAULT 121 NOT NULL,
    financiero_bajo_desde    NUMBER(14,0) DEFAULT 0 NOT NULL,
    financiero_bajo_hasta    NUMBER(14,0) DEFAULT 999999 NOT NULL,
    financiero_medio_desde   NUMBER(14,0) DEFAULT 1000000 NOT NULL,
    financiero_medio_hasta   NUMBER(14,0) DEFAULT 1999999 NOT NULL,
    financiero_alto_desde    NUMBER(14,0) DEFAULT 2000000 NOT NULL,
    CONSTRAINT pk_conf_impacto_nc PRIMARY KEY (id),
    CONSTRAINT ck_conf_imp_pred_nc CHECK (predeterminada IN (0, 1)),
    CONSTRAINT ck_conf_imp_clientes_nc CHECK (
        clientes_bajo_desde >= 0 AND
        clientes_bajo_desde <= clientes_bajo_hasta AND
        clientes_bajo_hasta < clientes_medio_desde AND
        clientes_medio_desde <= clientes_medio_hasta AND
        clientes_medio_hasta < clientes_alto_desde),
    CONSTRAINT ck_conf_imp_tiempo_nc CHECK (
        tiempo_bajo_desde >= 0 AND
        tiempo_bajo_desde <= tiempo_bajo_hasta AND
        tiempo_bajo_hasta < tiempo_medio_desde AND
        tiempo_medio_desde <= tiempo_medio_hasta AND
        tiempo_medio_hasta < tiempo_alto_desde),
    CONSTRAINT ck_conf_imp_fin_nc CHECK (
        financiero_bajo_desde >= 0 AND
        financiero_bajo_desde <= financiero_bajo_hasta AND
        financiero_bajo_hasta < financiero_medio_desde AND
        financiero_medio_desde <= financiero_medio_hasta AND
        financiero_medio_hasta < financiero_alto_desde)
);

CREATE TABLE tbl_configuracion_urgencia_nc (
    id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                              (START WITH 1 INCREMENT BY 1 CACHE 100),
    codigo                NVARCHAR2(30) NOT NULL,
    nombre                NVARCHAR2(180) NOT NULL,
    activo                NUMBER(1) DEFAULT 1 NOT NULL,
    tiempo_bajo_desde     NUMBER(10) DEFAULT 0 NOT NULL,
    tiempo_bajo_hasta     NUMBER(10) DEFAULT 27 NOT NULL,
    tiempo_medio_desde    NUMBER(10) DEFAULT 28 NOT NULL,
    tiempo_medio_hasta    NUMBER(10) DEFAULT 32 NOT NULL,
    tiempo_alto_desde     NUMBER(10) DEFAULT 33 NOT NULL,
    CONSTRAINT pk_conf_urgencia_nc PRIMARY KEY (id),
    CONSTRAINT uk_conf_urg_codigo_nc UNIQUE (codigo),
    CONSTRAINT ck_conf_urg_codigo_nc CHECK
        (codigo IN ('FACTURACION', 'POST_FACTURACION')),
    CONSTRAINT ck_conf_urg_activo_nc CHECK (activo IN (0, 1)),
    CONSTRAINT ck_conf_urg_rangos_nc CHECK (
        tiempo_bajo_desde >= 0 AND
        tiempo_bajo_desde <= tiempo_bajo_hasta AND
        tiempo_bajo_hasta < tiempo_medio_desde AND
        tiempo_medio_desde <= tiempo_medio_hasta AND
        tiempo_medio_hasta < tiempo_alto_desde)
);

CREATE TABLE tbl_pregunta_causa_nc (
    codigo        NVARCHAR2(30) NOT NULL,
    categoria_id  NUMBER(19) NOT NULL,
    texto         NCLOB NOT NULL,
    orden         NUMBER(5) NOT NULL,
    activo        NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_pregunta_causa_nc PRIMARY KEY (codigo),
    CONSTRAINT ck_pregunta_orden_nc CHECK (orden >= 0),
    CONSTRAINT ck_pregunta_activo_nc CHECK (activo IN (0, 1))
);

CREATE TABLE tbl_auditoria_administracion_nc (
    id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                    (START WITH 1 INCREMENT BY 1 CACHE 100),
    usuario_id  NUMBER(19) NOT NULL,
    fecha       TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    entidad     NVARCHAR2(100) NOT NULL,
    objeto      NVARCHAR2(100) NOT NULL,
    accion      NVARCHAR2(70) NOT NULL,
    antes       NCLOB NOT NULL,
    despues     NCLOB NOT NULL,
    CONSTRAINT pk_auditoria_admin_nc PRIMARY KEY (id),
    CONSTRAINT ck_auditoria_antes_nc CHECK (antes IS JSON (STRICT)),
    CONSTRAINT ck_auditoria_desp_nc CHECK (despues IS JSON (STRICT))
);

CREATE TABLE tbl_correlativo_sac_nc (
    id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                       (START WITH 1 INCREMENT BY 1 CACHE 100),
    anio           NUMBER(5) NOT NULL,
    ambito         NVARCHAR2(10) NOT NULL,
    ultimo_numero  NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_correlativo_sac_nc PRIMARY KEY (id),
    CONSTRAINT uk_correlativo_sac_nc UNIQUE (anio, ambito),
    CONSTRAINT ck_correlativo_anio_nc CHECK (anio >= 2000),
    CONSTRAINT ck_correlativo_num_nc CHECK (ultimo_numero >= 0)
);

CREATE TABLE tbl_registro_general_nc (
    id                              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                                        (START WITH 1 INCREMENT BY 1 CACHE 100),
    codigo                          NVARCHAR2(40) NOT NULL,
    titulo                          NVARCHAR2(250) NOT NULL,
    descripcion                     NCLOB,
    ticket_remedy                   NVARCHAR2(120),
    fecha_deteccion                 TIMESTAMP(6),
    fecha_registro                  TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    fecha_solucion                  DATE,
    impacto_clientes                NUMBER(5),
    impacto_tiempo                  NUMBER(5),
    impacto_soles                   NUMBER(5),
    impacto_resultante              NUMBER(5),
    prioridad_snapshot              NVARCHAR2(180),
    aplica_impacto                  NUMBER(1) DEFAULT 1 NOT NULL,
    justificacion_no_impacto        NCLOB,
    es_critica                      NVARCHAR2(2),
    origen_tecnologico              NUMBER(1) DEFAULT 0 NOT NULL,
    criterio_categoria              NCLOB,
    requisito_referencia            NCLOB,
    version                         NUMBER(10) DEFAULT 1 NOT NULL,
    updated_at                      TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    estado                          NVARCHAR2(30) DEFAULT 'BORRADOR' NOT NULL,
    proceso_id                      NUMBER(19) NOT NULL,
    registrado_por_id               NUMBER(19) NOT NULL,
    responsable_id                  NUMBER(19) NOT NULL,
    subproceso_id                   NUMBER(19),
    updated_by_id                   NUMBER(19),
    tipo_registro_id                NUMBER(19) NOT NULL,
    fuente_deteccion_id             NUMBER(19),
    urgencia_id                     NUMBER(19),
    prioridad_id                    NUMBER(19),
    actividad                       NVARCHAR2(250),
    impacto_clientes_seleccion      NVARCHAR2(180),
    impacto_financiero_seleccion    NVARCHAR2(180),
    impacto_tiempo_seleccion        NVARCHAR2(180),
    urgencia_area                   NVARCHAR2(80),
    urgencia_seleccion              NVARCHAR2(180),
    CONSTRAINT pk_registro_general_nc PRIMARY KEY (id),
    CONSTRAINT uk_registro_codigo_nc UNIQUE (codigo),
    CONSTRAINT ck_reg_aplica_imp_nc CHECK (aplica_impacto IN (0, 1)),
    CONSTRAINT ck_reg_origen_tec_nc CHECK (origen_tecnologico IN (0, 1)),
    CONSTRAINT ck_reg_version_nc CHECK (version >= 0),
    CONSTRAINT ck_reg_imp_clientes_nc CHECK
        (impacto_clientes IS NULL OR impacto_clientes BETWEEN 1 AND 3),
    CONSTRAINT ck_reg_imp_tiempo_nc CHECK
        (impacto_tiempo IS NULL OR impacto_tiempo BETWEEN 1 AND 3),
    CONSTRAINT ck_reg_imp_soles_nc CHECK
        (impacto_soles IS NULL OR impacto_soles BETWEEN 1 AND 3),
    CONSTRAINT ck_reg_imp_result_nc CHECK
        (impacto_resultante IS NULL OR impacto_resultante BETWEEN 1 AND 3),
    CONSTRAINT ck_reg_critica_nc CHECK
        (es_critica IS NULL OR es_critica IN ('SI', 'NO', 'NA'))
);

CREATE TABLE tbl_ciclo_tratamiento_nc (
    id                       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                                 (START WITH 1 INCREMENT BY 1 CACHE 100),
    hallazgo_id              NUMBER(19) NOT NULL,
    numero                   NUMBER(10) NOT NULL,
    motivo                   NCLOB NOT NULL,
    creado_por_id            NUMBER(19) NOT NULL,
    fecha_inicio             TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    fecha_fin                TIMESTAMP(6),
    analisis_responsable_id  NUMBER(19),
    analisis_inicio          TIMESTAMP(6),
    analisis_fin             TIMESTAMP(6),
    causa_raiz               NCLOB,
    checklist_snapshot       NCLOB NOT NULL,
    respuestas               NCLOB NOT NULL,
    control                  NCLOB NOT NULL,
    responsable_cierre_id    NUMBER(19),
    fecha_cierre             TIMESTAMP(6),
    comentarios_cierre       NCLOB,
    resultado_cierre         NVARCHAR2(12),
    CONSTRAINT pk_ciclo_tratamiento_nc PRIMARY KEY (id),
    CONSTRAINT uk_ciclo_hallazgo_nc UNIQUE (hallazgo_id, numero),
    CONSTRAINT ck_ciclo_numero_nc CHECK (numero >= 0),
    CONSTRAINT ck_ciclo_check_json_nc CHECK (checklist_snapshot IS JSON (STRICT)),
    CONSTRAINT ck_ciclo_resp_json_nc CHECK (respuestas IS JSON (STRICT)),
    CONSTRAINT ck_ciclo_ctrl_json_nc CHECK (control IS JSON (STRICT)),
    CONSTRAINT ck_ciclo_resultado_nc CHECK
        (resultado_cierre IS NULL OR resultado_cierre IN ('EFICAZ', 'NO_EFICAZ'))
);

CREATE TABLE tbl_actividad_nc (
    id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                            (START WITH 1 INCREMENT BY 1 CACHE 100),
    codigo              NVARCHAR2(50) NOT NULL,
    tipo                NVARCHAR2(18) NOT NULL,
    descripcion         NCLOB NOT NULL,
    fecha_inicio        DATE NOT NULL,
    fet_inicial         DATE,
    fecha_vigente       DATE,
    fecha_real          DATE,
    estado              NVARCHAR2(12) DEFAULT 'PENDIENTE' NOT NULL,
    porcentaje_avance   NUMBER(5) DEFAULT 0 NOT NULL,
    resultado_esperado  NCLOB NOT NULL,
    comentario          NCLOB,
    created_at          TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    responsable_id      NUMBER(19),
    ciclo_id            NUMBER(19) NOT NULL,
    CONSTRAINT pk_actividad_nc PRIMARY KEY (id),
    CONSTRAINT uk_actividad_codigo_nc UNIQUE (codigo),
    CONSTRAINT ck_actividad_avance_nc CHECK (porcentaje_avance BETWEEN 0 AND 100),
    CONSTRAINT ck_actividad_tipo_nc CHECK
        (tipo IN ('INMEDIATA', 'ACCION_INMEDIATA', 'CORRECTIVA')),
    CONSTRAINT ck_actividad_estado_nc CHECK
        (estado IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA')),
    CONSTRAINT ck_actividad_fet_nc CHECK
        (fet_inicial IS NULL OR fet_inicial >= fecha_inicio),
    CONSTRAINT ck_actividad_vigente_nc CHECK
        (fecha_vigente IS NULL OR fecha_vigente >= fecha_inicio),
    CONSTRAINT ck_actividad_real_nc CHECK
        (fecha_real IS NULL OR fecha_real >= fecha_inicio),
    CONSTRAINT ck_actividad_completa_nc CHECK (
        (estado = 'COMPLETADA' AND porcentaje_avance = 100 AND fecha_real IS NOT NULL)
        OR
        (estado <> 'COMPLETADA' AND porcentaje_avance < 100 AND fecha_real IS NULL)
    )
);

CREATE TABLE tbl_pbi_nc (
    id                 NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                           (START WITH 1 INCREMENT BY 1 CACHE 100),
    ciclo_id           NUMBER(19) NOT NULL,
    numero_pbi         NVARCHAR2(100) NOT NULL,
    ticket_incidente   NVARCHAR2(100),
    sistema            NVARCHAR2(200) NOT NULL,
    herramienta        NVARCHAR2(100) DEFAULT 'Helix (registro manual)' NOT NULL,
    responsable_ti_id  NUMBER(19) NOT NULL,
    estado             NVARCHAR2(10) DEFAULT 'ABIERTO' NOT NULL,
    fecha_creacion     TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    fecha_cierre_pbi   DATE,
    observacion        NCLOB,
    CONSTRAINT pk_pbi_nc PRIMARY KEY (id),
    CONSTRAINT uk_pbi_ciclo_numero_nc UNIQUE (ciclo_id, numero_pbi),
    CONSTRAINT ck_pbi_estado_nc CHECK (estado IN ('ABIERTO', 'CERRADO')),
    CONSTRAINT ck_pbi_cierre_nc CHECK (
        (estado = 'ABIERTO' AND fecha_cierre_pbi IS NULL)
        OR
        (estado = 'CERRADO' AND fecha_cierre_pbi IS NOT NULL)
    )
);

CREATE TABLE tbl_evaluacion_eficacia_nc (
    id                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                          (START WITH 1 INCREMENT BY 1 CACHE 100),
    ciclo_id          NUMBER(19) NOT NULL,
    evaluador_id      NUMBER(19) NOT NULL,
    fecha_evaluacion  DATE NOT NULL,
    resultado         NVARCHAR2(12) NOT NULL,
    comentario        NCLOB NOT NULL,
    fecha_registro    TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    CONSTRAINT pk_evaluacion_eficacia_nc PRIMARY KEY (id),
    CONSTRAINT ck_eval_resultado_nc CHECK
        (resultado IN ('EFICAZ', 'NO_EFICAZ'))
);

CREATE TABLE tbl_comunicacion_nc (
    id                 NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                           (START WITH 1 INCREMENT BY 1 CACHE 100),
    ciclo_id           NUMBER(19) NOT NULL,
    registrado_por_id  NUMBER(19) NOT NULL,
    destinatarios      NVARCHAR2(500) NOT NULL,
    medio              NVARCHAR2(120) NOT NULL,
    descripcion        NCLOB NOT NULL,
    fecha              TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    CONSTRAINT pk_comunicacion_nc PRIMARY KEY (id)
);

CREATE TABLE tbl_evidencia_nc (
    id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                         (START WITH 1 INCREMENT BY 1 CACHE 100),
    hallazgo_id      NUMBER(19) NOT NULL,
    accion_id        NUMBER(19),
    analisis_id      NUMBER(19),
    evaluacion_id    NUMBER(19),
    cierre_id        NUMBER(19),
    archivo          NVARCHAR2(100) NOT NULL,
    nombre_original  NVARCHAR2(255) NOT NULL,
    mime_type        NVARCHAR2(100) NOT NULL,
    tamanio          NUMBER(10) NOT NULL,
    subido_por_id    NUMBER(19) NOT NULL,
    fecha_carga      TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    descripcion      NCLOB,
    CONSTRAINT pk_evidencia_nc PRIMARY KEY (id),
    CONSTRAINT ck_evidencia_tamanio_nc CHECK (tamanio > 0),
    CONSTRAINT ck_evidencia_contexto_nc CHECK (
        (CASE WHEN accion_id IS NULL THEN 0 ELSE 1 END) +
        (CASE WHEN analisis_id IS NULL THEN 0 ELSE 1 END) +
        (CASE WHEN evaluacion_id IS NULL THEN 0 ELSE 1 END) +
        (CASE WHEN cierre_id IS NULL THEN 0 ELSE 1 END) <= 1
    )
);

CREATE TABLE tbl_archivo_evidencia_nc (
    id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                      (START WITH 1 INCREMENT BY 1 CACHE 100),
    contenido     BLOB NOT NULL,
    sha256        NVARCHAR2(64) NOT NULL,
    evidencia_id  NUMBER(19) NOT NULL,
    CONSTRAINT pk_archivo_evidencia_nc PRIMARY KEY (id),
    CONSTRAINT uk_archivo_evidencia_nc UNIQUE (evidencia_id),
    CONSTRAINT ck_archivo_sha256_nc CHECK
        (REGEXP_LIKE(sha256, '^[0-9A-Fa-f]{64}$'))
);

CREATE TABLE tbl_historial_hallazgo_nc (
    id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                              (START WITH 1 INCREMENT BY 1 CACHE 100),
    accion_relacionada_id  NUMBER(19),
    hallazgo_id            NUMBER(19) NOT NULL,
    usuario_id             NUMBER(19) NOT NULL,
    fecha_hora             TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    accion                 NVARCHAR2(70) NOT NULL,
    estado_anterior        NVARCHAR2(30),
    estado_nuevo           NVARCHAR2(30),
    comentario             NCLOB,
    metadata_json          NCLOB NOT NULL,
    CONSTRAINT pk_historial_hallazgo_nc PRIMARY KEY (id),
    CONSTRAINT ck_historial_json_nc CHECK (metadata_json IS JSON (STRICT))
);

CREATE TABLE tbl_notificacion_nc (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                        (START WITH 1 INCREMENT BY 1 CACHE 100),
    usuario_id      NUMBER(19) NOT NULL,
    hallazgo_id     NUMBER(19) NOT NULL,
    tipo            NVARCHAR2(50) NOT NULL,
    titulo          NVARCHAR2(250) NOT NULL,
    mensaje         NCLOB NOT NULL,
    leida           NUMBER(1) DEFAULT 0 NOT NULL,
    fecha_creacion  TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    fecha_lectura   TIMESTAMP(6),
    CONSTRAINT pk_notificacion_nc PRIMARY KEY (id),
    CONSTRAINT ck_notificacion_leida_nc CHECK (leida IN (0, 1)),
    CONSTRAINT ck_notificacion_fecha_nc CHECK
        ((leida = 0 AND fecha_lectura IS NULL) OR leida = 1)
);

CREATE TABLE tbl_django_migrations_nc (
    id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY
                 (START WITH 1 INCREMENT BY 1 CACHE 100),
    app      NVARCHAR2(255) NOT NULL,
    name     NVARCHAR2(255) NOT NULL,
    applied  TIMESTAMP(6) DEFAULT LOCALTIMESTAMP NOT NULL,
    CONSTRAINT pk_django_migrations_nc PRIMARY KEY (id),
    CONSTRAINT uk_django_migration_nc UNIQUE (app, name)
);

CREATE TABLE tbl_django_session_nc (
    session_key   NVARCHAR2(40) NOT NULL,
    session_data  NCLOB NOT NULL,
    expire_date   TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_django_session_nc PRIMARY KEY (session_key)
);

PROMPT OK: 24 tablas creadas.
