PROMPT [7/9] Permisos para USRFACSOP

GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_usuario_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_usuario_rol_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_catalogo_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_proceso_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_proceso_validador_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_subproceso_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_matriz_prioridad_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_configuracion_impacto_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_configuracion_urgencia_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_pregunta_causa_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_auditoria_administracion_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_correlativo_sac_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_registro_general_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_ciclo_tratamiento_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_actividad_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_pbi_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_evaluacion_eficacia_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_comunicacion_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_evidencia_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_archivo_evidencia_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_historial_hallazgo_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_notificacion_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_django_migrations_nc
    TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_django_session_nc
    TO USRFACSOP;

PROMPT OK: permisos DML concedidos sobre las 24 tablas al usuario USRFACSOP.
