-- Permisos de la cuenta técnica para un esquema Portal NC ya instalado.
-- Ejecutar conectado como USRFACT. Es seguro volver a ejecutarlo.
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
    v_tablas   PLS_INTEGER;
    v_usuario  PLS_INTEGER;
BEGIN
    IF UPPER(USER) <> 'USRFACT' THEN
        RAISE_APPLICATION_ERROR(-20401,
            'Conectese como USRFACT. Usuario actual: ' || USER);
    END IF;

    SELECT COUNT(*) INTO v_usuario
      FROM ALL_USERS
     WHERE USERNAME = 'USRFACSOP';
    IF v_usuario <> 1 THEN
        RAISE_APPLICATION_ERROR(-20402,
            'La cuenta tecnica USRFACSOP no existe en esta base Oracle.');
    END IF;

    SELECT COUNT(*) INTO v_tablas
      FROM USER_TABLES
     WHERE TABLE_NAME IN (
        'TBL_USUARIO_NC','TBL_USUARIO_ROL_NC','TBL_CATALOGO_NC',
        'TBL_PROCESO_NC','TBL_PROCESO_VALIDADOR_NC','TBL_SUBPROCESO_NC',
        'TBL_MATRIZ_PRIORIDAD_NC','TBL_CONFIGURACION_IMPACTO_NC',
        'TBL_CONFIGURACION_URGENCIA_NC','TBL_PREGUNTA_CAUSA_NC',
        'TBL_AUDITORIA_ADMINISTRACION_NC','TBL_CORRELATIVO_SAC_NC',
        'TBL_REGISTRO_GENERAL_NC','TBL_CICLO_TRATAMIENTO_NC',
        'TBL_ACTIVIDAD_NC','TBL_PBI_NC','TBL_EVALUACION_EFICACIA_NC',
        'TBL_COMUNICACION_NC','TBL_EVIDENCIA_NC','TBL_ARCHIVO_EVIDENCIA_NC',
        'TBL_HISTORIAL_HALLAZGO_NC','TBL_NOTIFICACION_NC',
        'TBL_DJANGO_MIGRATIONS_NC','TBL_DJANGO_SESSION_NC'
     );
    IF v_tablas <> 24 THEN
        RAISE_APPLICATION_ERROR(-20403,
            'Se esperaban 24 tablas del Portal NC y existen ' || v_tablas || '.');
    END IF;
END;
/

GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_usuario_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_usuario_rol_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_catalogo_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_proceso_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_proceso_validador_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_subproceso_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_matriz_prioridad_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_configuracion_impacto_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_configuracion_urgencia_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_pregunta_causa_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_auditoria_administracion_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_correlativo_sac_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_registro_general_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_ciclo_tratamiento_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_actividad_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_pbi_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_evaluacion_eficacia_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_comunicacion_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_evidencia_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_archivo_evidencia_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_historial_hallazgo_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_notificacion_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_django_migrations_nc TO USRFACSOP;
GRANT SELECT, INSERT, UPDATE, DELETE ON tbl_django_session_nc TO USRFACSOP;

DECLARE
    v_permisos PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_permisos
      FROM USER_TAB_PRIVS_MADE
     WHERE GRANTEE = 'USRFACSOP'
       AND PRIVILEGE IN ('SELECT','INSERT','UPDATE','DELETE')
       AND TABLE_NAME IN (
        'TBL_USUARIO_NC','TBL_USUARIO_ROL_NC','TBL_CATALOGO_NC',
        'TBL_PROCESO_NC','TBL_PROCESO_VALIDADOR_NC','TBL_SUBPROCESO_NC',
        'TBL_MATRIZ_PRIORIDAD_NC','TBL_CONFIGURACION_IMPACTO_NC',
        'TBL_CONFIGURACION_URGENCIA_NC','TBL_PREGUNTA_CAUSA_NC',
        'TBL_AUDITORIA_ADMINISTRACION_NC','TBL_CORRELATIVO_SAC_NC',
        'TBL_REGISTRO_GENERAL_NC','TBL_CICLO_TRATAMIENTO_NC',
        'TBL_ACTIVIDAD_NC','TBL_PBI_NC','TBL_EVALUACION_EFICACIA_NC',
        'TBL_COMUNICACION_NC','TBL_EVIDENCIA_NC','TBL_ARCHIVO_EVIDENCIA_NC',
        'TBL_HISTORIAL_HALLAZGO_NC','TBL_NOTIFICACION_NC',
        'TBL_DJANGO_MIGRATIONS_NC','TBL_DJANGO_SESSION_NC'
       );
    IF v_permisos <> 96 THEN
        RAISE_APPLICATION_ERROR(-20404,
            'USRFACSOP debe tener 96 permisos DML y tiene ' || v_permisos || '.');
    END IF;
    DBMS_OUTPUT.PUT_LINE(
        'OK: USRFACSOP tiene SELECT, INSERT, UPDATE y DELETE sobre las 24 tablas.');
END;
/

EXIT SUCCESS
