# Generated by Django 5.2.17 on 2026-09-22 00:33

import apps.hallazgos.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisCausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa_raiz', models.TextField(blank=True)),
                ('checklist_snapshot', models.JSONField(blank=True, default=list)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='analisis', to='hallazgos.ciclotratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('INMEDIATA', 'Acción inmediata'), ('CORRECTIVA', 'Acción correctiva')], max_length=12)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fet_inicial', models.DateField()),
                ('fecha_vigente', models.DateField()),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=12)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('resultado_esperado', models.TextField()),
                ('comentario', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='hallazgos.ciclotratamiento')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CierreHallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField()),
                ('resultado', models.CharField(default='EFICAZ', max_length=12)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='hallazgos.ciclotratamiento')),
                ('responsable_cierre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComunicacionHallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.CharField(max_length=500)),
                ('medio', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones', to='hallazgos.ciclotratamiento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ControlProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.JSONField(default=list)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('mitiga_riesgo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No aplica')], max_length=2)),
                ('frecuencia', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=200)),
                ('evidencia', models.TextField()),
                ('analisis', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='control', to='hallazgos.analisiscausa')),
            ],
        ),
        migrations.CreateModel(
            name='CorrelativoSAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('ambito', models.CharField(max_length=10)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('anio', 'ambito'), name='sac_anio_ambito_unico')],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionEficacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('resultado', models.CharField(choices=[('EFICAZ', 'Eficaz'), ('NO_EFICAZ', 'No eficaz')], max_length=12)),
                ('comentario', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='hallazgos.ciclotratamiento')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=40, unique=True)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('ticket_remedy', models.CharField(blank=True, max_length=120)),
                ('fecha_deteccion', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_solucion', models.DateField(blank=True, null=True)),
                ('impacto_clientes', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('impacto_tiempo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('impacto_soles', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('impacto_resultante', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('prioridad_snapshot', models.CharField(blank=True, editable=False, max_length=180)),
                ('aplica_impacto', models.BooleanField(default=True)),
                ('justificacion_no_impacto', models.TextField(blank=True)),
                ('es_critica', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No aplica')], max_length=2)),
                ('origen_tecnologico', models.BooleanField(default=False)),
                ('criterio_categoria', models.TextField(blank=True)),
                ('requisito_referencia', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(default='BORRADOR', on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadohallazgo')),
                ('fuente_deteccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.fuentedeteccion')),
                ('prioridad', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.prioridad')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.proceso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_registrados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_responsable', to=settings.AUTH_USER_MODEL)),
                ('subproceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.subproceso')),
                ('tipo_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tiporegistro')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('urgencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.urgencia')),
            ],
            options={
                'ordering': ['-fecha_registro', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.hallazgos.models.ruta_evidencia)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('tamanio', models.PositiveIntegerField()),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True)),
                ('accion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='hallazgos.accion')),
                ('analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='hallazgos.analisiscausa')),
                ('cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='hallazgos.cierrehallazgo')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='hallazgos.evaluacioneficacia')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='hallazgos.hallazgo')),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='cierrehallazgo',
            name='hallazgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to='hallazgos.hallazgo'),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='hallazgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='hallazgos.hallazgo'),
        ),
        migrations.CreateModel(
            name='HistorialHallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.CharField(max_length=70)),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('comentario', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='hallazgos.hallazgo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=250)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='hallazgos.hallazgo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PBI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pbi', models.CharField(max_length=100)),
                ('ticket_incidente', models.CharField(blank=True, max_length=100)),
                ('sistema', models.CharField(max_length=200)),
                ('herramienta', models.CharField(default='Helix (registro manual)', max_length=100)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pbis', to='hallazgos.ciclotratamiento')),
                ('responsable_ti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReprogramacionAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reprogramacion', models.PositiveSmallIntegerField()),
                ('fecha_anterior', models.DateField()),
                ('nueva_fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reprogramaciones', to='hallazgos.accion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero_reprogramacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_snapshot', models.CharField(max_length=8)),
                ('texto_snapshot', models.TextField()),
                ('respuesta', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('NA', 'No aplica')], max_length=2)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='hallazgos.analisiscausa')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.preguntacausa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pregunta__categoria__orden', 'pregunta__orden'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada')], max_length=12)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguimientos', to='hallazgos.accion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='accion',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_avance__lte', 100)), name='accion_avance_max_100'),
        ),
        migrations.AddConstraint(
            model_name='accion',
            constraint=models.CheckConstraint(condition=models.Q(('fet_inicial__gte', models.F('fecha_inicio'))), name='accion_fet_desde_inicio'),
        ),
        migrations.AddConstraint(
            model_name='accion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vigente__gte', models.F('fecha_inicio'))), name='accion_vigente_desde_inicio'),
        ),
        migrations.AddConstraint(
            model_name='accion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_real__isnull', True), ('fecha_real__gte', models.F('fecha_inicio')), _connector='OR'), name='accion_real_desde_inicio'),
        ),
        migrations.AddConstraint(
            model_name='accion',
            constraint=models.CheckConstraint(condition=models.Q(('tipo__in', ['INMEDIATA', 'CORRECTIVA'])), name='accion_tipo_valido'),
        ),
        migrations.AddConstraint(
            model_name='accion',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'EN_PROCESO', 'COMPLETADA'])), name='accion_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='accion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'COMPLETADA'), ('fecha_real__isnull', False), ('porcentaje_avance', 100)), models.Q(models.Q(('estado', 'COMPLETADA'), _negated=True), ('fecha_real__isnull', True), ('porcentaje_avance__lt', 100)), _connector='OR'), name='accion_completada_coherente'),
        ),
        migrations.AddConstraint(
            model_name='evaluacioneficacia',
            constraint=models.CheckConstraint(condition=models.Q(('resultado__in', ['EFICAZ', 'NO_EFICAZ'])), name='eficacia_resultado_valido'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(fields=['estado', 'fecha_registro'], name='hallazgos_h_estado__937a29_idx'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(fields=['responsable', 'estado'], name='hallazgos_h_respons_9b79b5_idx'),
        ),
        migrations.AddIndex(
            model_name='hallazgo',
            index=models.Index(fields=['proceso', 'fecha_solucion'], name='hallazgos_h_proceso_3a856a_idx'),
        ),
        migrations.AddConstraint(
            model_name='hallazgo',
            constraint=models.CheckConstraint(condition=models.Q(('impacto_clientes__isnull', True), ('impacto_clientes__range', (1, 3)), _connector='OR'), name='impacto_clientes_rango'),
        ),
        migrations.AddConstraint(
            model_name='hallazgo',
            constraint=models.CheckConstraint(condition=models.Q(('impacto_tiempo__isnull', True), ('impacto_tiempo__range', (1, 3)), _connector='OR'), name='impacto_tiempo_rango'),
        ),
        migrations.AddConstraint(
            model_name='hallazgo',
            constraint=models.CheckConstraint(condition=models.Q(('impacto_soles__isnull', True), ('impacto_soles__range', (1, 3)), _connector='OR'), name='impacto_soles_rango'),
        ),
        migrations.AddConstraint(
            model_name='hallazgo',
            constraint=models.CheckConstraint(condition=models.Q(('impacto_resultante__isnull', True), ('impacto_resultante__range', (1, 3)), _connector='OR'), name='impacto_resultante_rango'),
        ),
        migrations.AddConstraint(
            model_name='hallazgo',
            constraint=models.CheckConstraint(condition=models.Q(('es_critica__in', ['SI', 'NO', 'NA', ''])), name='hallazgo_criticidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='evidencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accion__isnull', True), ('analisis__isnull', True), ('evaluacion__isnull', True)), models.Q(('accion__isnull', True), ('analisis__isnull', True), ('cierre__isnull', True)), models.Q(('accion__isnull', True), ('cierre__isnull', True), ('evaluacion__isnull', True)), models.Q(('analisis__isnull', True), ('cierre__isnull', True), ('evaluacion__isnull', True)), _connector='OR'), name='evidencia_un_contexto_maximo'),
        ),
        migrations.AddConstraint(
            model_name='ciclotratamiento',
            constraint=models.UniqueConstraint(fields=('hallazgo', 'numero'), name='ciclo_hallazgo_numero_unico'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida', 'fecha_creacion'], name='hallazgos_n_usuario_f00322_idx'),
        ),
        migrations.AddConstraint(
            model_name='pbi',
            constraint=models.UniqueConstraint(fields=('ciclo', 'numero_pbi'), name='pbi_referencia_ciclo_unico'),
        ),
        migrations.AddConstraint(
            model_name='pbi',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ABIERTO'), ('fecha_cierre__isnull', True)), models.Q(('estado', 'CERRADO'), ('fecha_cierre__isnull', False)), _connector='OR'), name='pbi_cierre_coherente'),
        ),
        migrations.AddConstraint(
            model_name='reprogramacionaccion',
            constraint=models.UniqueConstraint(fields=('accion', 'numero_reprogramacion'), name='reprogramacion_numero_unico'),
        ),
        migrations.AddConstraint(
            model_name='reprogramacionaccion',
            constraint=models.CheckConstraint(condition=models.Q(('numero_reprogramacion__range', (1, 3))), name='max_tres_reprogramaciones'),
        ),
        migrations.AddConstraint(
            model_name='respuestacausa',
            constraint=models.UniqueConstraint(fields=('analisis', 'pregunta'), name='respuesta_analisis_pregunta_unica'),
        ),
        migrations.AddConstraint(
            model_name='respuestacausa',
            constraint=models.CheckConstraint(condition=models.Q(('respuesta__in', ['SI', 'NO', 'NA'])), name='respuesta_causa_valida'),
        ),
        migrations.AddConstraint(
            model_name='seguimientoaccion',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_avance__lte', 100)), name='seguimiento_avance_max_100'),
        ),
    ]
