# Generated by Django 5.2.17 on 2026-09-22 15:35

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def consolidar_tratamiento(apps, schema_editor):
    alias = schema_editor.connection.alias
    def qs(name, app="hallazgos"):
        return apps.get_model(app, name).objects.using(alias)
    mapas = {(c.clase, c.codigo): c.pk for c in qs("Catalogo", "catalogos").all()}
    for h in qs("Hallazgo").all():
        for nombre, clase in [("tipo_registro", "TIPO"), ("fuente_deteccion", "FUENTE"), ("urgencia", "URGENCIA"), ("prioridad", "PRIORIDAD")]:
            viejo = getattr(h, nombre + "_id")
            setattr(h, nombre + "_nuevo_id", mapas[(clase, str(viejo))] if viejo is not None else None)
        h.save(using=alias, update_fields=["tipo_registro_nuevo", "fuente_deteccion_nuevo", "urgencia_nuevo", "prioridad_nuevo"])
    for a in qs("AnalisisCausa").all():
        respuestas = [dict(id=r.pk, pregunta_id=r.pregunta_id, codigo_snapshot=r.codigo_snapshot, texto_snapshot=r.texto_snapshot, respuesta=r.respuesta, comentario=r.comentario, usuario_id=r.usuario_id, fecha=r.fecha.isoformat()) for r in qs("RespuestaCausa").filter(analisis_id=a.pk).order_by("pk")]
        control = qs("ControlProceso").filter(analisis_id=a.pk).first()
        datos_control = {k: getattr(control, k) for k in ["tipos", "nombre", "descripcion", "mitiga_riesgo", "frecuencia", "responsable", "evidencia"]} if control else {}
        qs("CicloTratamiento").filter(pk=a.ciclo_id).update(analisis_responsable_id=a.responsable_id, analisis_inicio=a.fecha_inicio, analisis_fin=a.fecha_finalizacion, causa_raiz=a.causa_raiz, checklist_snapshot=a.checklist_snapshot, respuestas=respuestas, control=datos_control)
        qs("Evidencia").filter(analisis_id=a.pk).update(analisis_nuevo_id=a.ciclo_id)
    vistos = set()
    for c in qs("CierreHallazgo").all():
        if c.ciclo_id in vistos:
            raise RuntimeError("Hay varios cierres para un mismo ciclo; no se elimina información. Revisar antes de migrar.")
        vistos.add(c.ciclo_id)
        qs("CicloTratamiento").filter(pk=c.ciclo_id).update(responsable_cierre_id=c.responsable_cierre_id, fecha_cierre=c.fecha_cierre, comentarios_cierre=c.observaciones, resultado_cierre=c.resultado)
        qs("Evidencia").filter(cierre_id=c.pk).update(cierre_nuevo_id=c.ciclo_id)
    for modelo, evento in [("SeguimientoAccion", "SEGUIMIENTO_ACCION"), ("ReprogramacionAccion", "REPROGRAMACION")]:
        for row in qs(modelo).select_related("accion__ciclo").all():
            a = row.accion
            if modelo == "SeguimientoAccion":
                fecha, comentario = row.fecha, row.comentario
                datos = dict(estado=row.estado, avance=row.porcentaje_avance)
            else:
                fecha, comentario = row.fecha_registro, row.motivo
                datos = dict(numero=row.numero_reprogramacion, fecha_anterior=str(row.fecha_anterior), nueva_fecha=str(row.nueva_fecha))
            datos.update(accion=a.codigo, origen_tabla=modelo, origen_id=row.pk, fecha_original=fecha.isoformat())
            # Reuse the existing audit entry when uniquely identifiable; otherwise retain a detailed entry.
            candidatos = qs("HistorialHallazgo").filter(hallazgo_id=a.ciclo.hallazgo_id, accion=evento, metadata_json__accion=a.codigo, usuario_id=row.usuario_id, comentario=comentario, accion_relacionada__isnull=True)
            if modelo == "ReprogramacionAccion":
                candidatos = candidatos.filter(metadata_json__numero=row.numero_reprogramacion)
            else:
                candidatos = candidatos.filter(metadata_json__avance=row.porcentaje_avance)
            existente = candidatos.first() if candidatos.count() == 1 else None
            if existente:
                existente.accion_relacionada_id = a.pk
                existente.metadata_json.update(datos)
                existente.save(using=alias, update_fields=["accion_relacionada", "metadata_json"])
            else:
                qs("HistorialHallazgo").create(hallazgo_id=a.ciclo.hallazgo_id, usuario_id=row.usuario_id, accion=evento, accion_relacionada_id=a.pk, fecha_hora=fecha, comentario=comentario, metadata_json=datos)

    # Flush deferred foreign-key checks before the following schema changes.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_catalogo_unificado'),
        ('hallazgos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='tipo_registro_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='fuente_deteccion_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='urgencia_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='prioridad_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='analisis_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analisis_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='analisis_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='analisis_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='causa_raiz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='checklist_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='respuestas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='control',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='responsable_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='comentarios_cierre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ciclotratamiento',
            name='resultado_cierre',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='historialhallazgo',
            name='accion_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='hallazgos.accion'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='analisis_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hallazgos.ciclotratamiento'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='cierre_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hallazgos.ciclotratamiento'),
        ),
        migrations.RunPython(
            code=consolidar_tratamiento,
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='tipo_registro',
        ),
        migrations.RenameField(
            model_name='hallazgo',
            old_name='tipo_registro_nuevo',
            new_name='tipo_registro',
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='tipo_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='fuente_deteccion',
        ),
        migrations.RenameField(
            model_name='hallazgo',
            old_name='fuente_deteccion_nuevo',
            new_name='fuente_deteccion',
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='fuente_deteccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='urgencia',
        ),
        migrations.RenameField(
            model_name='hallazgo',
            old_name='urgencia_nuevo',
            new_name='urgencia',
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='urgencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.RemoveField(
            model_name='hallazgo',
            name='prioridad',
        ),
        migrations.RenameField(
            model_name='hallazgo',
            old_name='prioridad_nuevo',
            new_name='prioridad',
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='prioridad',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_VALIDACION', 'Pendiente de validación'), ('DEVUELTO', 'Devuelto'), ('VALIDADO', 'Validado'), ('ACCION_INMEDIATA', 'Acción inmediata'), ('EN_ANALISIS', 'En análisis'), ('PBI_EN_GESTION', 'PBI en gestión'), ('PLAN_ACCION', 'Plan de acción'), ('EN_IMPLEMENTACION', 'En implementación'), ('EN_VERIFICACION', 'En verificación'), ('CERRADO', 'Cerrado'), ('REABIERTO', 'Reabierto'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=30),
        ),
        migrations.RemoveConstraint(
            model_name='evidencia',
            name='evidencia_un_contexto_maximo',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='analisis',
        ),
        migrations.RenameField(
            model_name='evidencia',
            old_name='analisis_nuevo',
            new_name='analisis',
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_analisis', to='hallazgos.ciclotratamiento'),
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='cierre',
        ),
        migrations.RenameField(
            model_name='evidencia',
            old_name='cierre_nuevo',
            new_name='cierre',
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_cierre', to='hallazgos.ciclotratamiento'),
        ),
        migrations.AddConstraint(
            model_name='evidencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accion__isnull', True), ('analisis__isnull', True), ('evaluacion__isnull', True)), models.Q(('accion__isnull', True), ('analisis__isnull', True), ('cierre__isnull', True)), models.Q(('accion__isnull', True), ('cierre__isnull', True), ('evaluacion__isnull', True)), models.Q(('analisis__isnull', True), ('cierre__isnull', True), ('evaluacion__isnull', True)), _connector='OR'), name='evidencia_un_contexto_maximo'),
        ),
        migrations.DeleteModel(
            name='RespuestaCausa',
        ),
        migrations.DeleteModel(
            name='ControlProceso',
        ),
        migrations.DeleteModel(
            name='AnalisisCausa',
        ),
        migrations.DeleteModel(
            name='CierreHallazgo',
        ),
        migrations.DeleteModel(
            name='SeguimientoAccion',
        ),
        migrations.DeleteModel(
            name='ReprogramacionAccion',
        ),
    ]
