# Generated by Django 5.2.17 on 2026-09-22 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_retirar_catalogos_separados'),
        ('hallazgos', '0002_tratamiento_compacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallazgo',
            name='tipo_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.tiporegistro'),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='fuente_deteccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.fuentedeteccion'),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='urgencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.urgencia'),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='prioridad',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.prioridad'),
        ),
    ]
