# Generated by Django 5.2.17 on 2026-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0003_catalogos_tipados'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroGeneral',
            fields=[
                ('fila_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hallazgo_id', models.BigIntegerField()),
                ('ciclo_id', models.BigIntegerField(null=True)),
                ('accion_id', models.BigIntegerField(null=True)),
                ('numero', models.BigIntegerField(null=True)),
                ('gerencia', models.TextField(null=True)),
                ('proceso', models.TextField(null=True)),
                ('sub_proceso', models.TextField(null=True)),
                ('fuente_deteccion', models.TextField(null=True)),
                ('tipo_hallazgo', models.TextField(null=True)),
                ('numero_hallazgo', models.TextField(null=True)),
                ('ticket_remedy', models.TextField(null=True)),
                ('descripcion_hallazgo', models.TextField(null=True)),
                ('requisito_referencia', models.TextField(null=True)),
                ('responsable_proceso', models.TextField(null=True)),
                ('fecha_deteccion', models.DateTimeField(null=True)),
                ('fecha_registro', models.DateTimeField(null=True)),
                ('impacto', models.TextField(null=True)),
                ('urgencia', models.TextField(null=True)),
                ('prioridad_criticidad', models.TextField(null=True)),
                ('no_conformidad_critica', models.TextField(null=True)),
                ('causas_raiz', models.TextField(null=True)),
                ('tipo_accion', models.TextField(null=True)),
                ('descripcion_accion', models.TextField(null=True)),
                ('responsable', models.TextField(null=True)),
                ('fet', models.DateField(null=True)),
                ('estado', models.TextField(null=True)),
                ('evidencia_implementacion', models.TextField(null=True)),
                ('porcentaje_avance', models.IntegerField(null=True)),
                ('comentario', models.TextField(null=True)),
                ('fecha_evaluacion_eficacia', models.DateField(null=True)),
                ('resultado_eficacia', models.TextField(null=True)),
                ('fecha_cierre', models.DateTimeField(null=True)),
                ('auditor_verificador', models.TextField(null=True)),
                ('comentarios', models.TextField(null=True)),
            ],
            options={
                'db_table': 'registro_general',
                'ordering': ['numero'],
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='hallazgo',
            new_name='hallazgos_h_estado_7a4480_idx',
            old_name='hallazgos_h_estado__937a29_idx',
        ),
        migrations.RenameIndex(
            model_name='hallazgo',
            new_name='hallazgos_h_respons_f759c0_idx',
            old_name='hallazgos_h_respons_9b79b5_idx',
        ),
    ]
