from django.db import migrations


# El ORM conserva estos nombres como vistas tipadas. Sus filas se concentran en
# una sola tabla auxiliar y un trigger de backend atiende las escrituras.
TABLAS_AUXILIARES = [
    "accounts_usuario_groups",
    "accounts_usuario_user_permissions",
    "auth_group",
    "auth_group_permissions",
    "auth_permission",
    "catalogos_auditoriaadministracion",
    "catalogos_matrizprioridad",
    "catalogos_preguntacausa",
    "catalogos_proceso_validadores",
    "catalogos_subproceso",
    "django_admin_log",
    "django_content_type",
    "django_session",
    "hallazgos_comunicacionhallazgo",
    "hallazgos_evaluacioneficacia",
    "hallazgos_evidencia",
    "hallazgos_notificacion",
    "hallazgos_pbi",
]


def compactar(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        raise RuntimeError("La compactación física requiere PostgreSQL.")

    nombres = ", ".join("'%s'" % nombre for nombre in TABLAS_AUXILIARES)
    schema_editor.execute(
        """
        CREATE TABLE IF NOT EXISTS sistema_registro_auxiliar (
            serial_id bigint GENERATED BY DEFAULT AS IDENTITY,
            tipo varchar(100) NOT NULL,
            clave varchar(255) NOT NULL,
            datos jsonb NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT sistema_registro_auxiliar_pk PRIMARY KEY (tipo, clave)
        );

        CREATE OR REPLACE FUNCTION sistema_registro_auxiliar_dml()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $func$
        DECLARE
            campo_pk text := TG_ARGV[0];
            payload jsonb;
            clave_nueva text;
            clave_anterior text;
            numero_generado bigint;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                clave_anterior := to_jsonb(OLD) ->> campo_pk;
                DELETE FROM sistema_registro_auxiliar
                 WHERE tipo = TG_TABLE_NAME AND clave = clave_anterior;
                RETURN OLD;
            END IF;

            payload := to_jsonb(NEW);
            clave_nueva := payload ->> campo_pk;
            IF clave_nueva IS NULL OR clave_nueva = '' THEN
                numero_generado := nextval(
                    pg_get_serial_sequence('sistema_registro_auxiliar', 'serial_id')
                );
                clave_nueva := numero_generado::text;
                payload := jsonb_set(payload, ARRAY[campo_pk], to_jsonb(numero_generado), true);
                NEW := jsonb_populate_record(NEW, payload);
            END IF;

            IF TG_OP = 'INSERT' THEN
                INSERT INTO sistema_registro_auxiliar(tipo, clave, datos)
                VALUES (TG_TABLE_NAME, clave_nueva, payload);
                RETURN NEW;
            END IF;

            clave_anterior := to_jsonb(OLD) ->> campo_pk;
            UPDATE sistema_registro_auxiliar
               SET clave = clave_nueva, datos = payload
             WHERE tipo = TG_TABLE_NAME AND clave = clave_anterior;
            RETURN NEW;
        END
        $func$;

        DO $compactar$
        DECLARE
            nombre text;
            tipo_fila text;
            columnas text;
            campo_pk text;
            restriccion record;
        BEGIN
            FOR restriccion IN
                SELECT conrelid::regclass::text AS tabla, conname
                  FROM pg_constraint
                 WHERE contype = 'f'
                   AND (
                       confrelid IN (
                           SELECT c.oid FROM pg_class c
                           JOIN pg_namespace n ON n.oid = c.relnamespace
                           WHERE n.nspname = 'public' AND c.relname IN (""" + nombres + """
                           )
                       )
                       OR conrelid IN (
                           SELECT c.oid FROM pg_class c
                           JOIN pg_namespace n ON n.oid = c.relnamespace
                           WHERE n.nspname = 'public' AND c.relname IN (""" + nombres + """
                           )
                       )
                   )
            LOOP
                EXECUTE format('ALTER TABLE %%s DROP CONSTRAINT %%I', restriccion.tabla, restriccion.conname);
            END LOOP;

            FOREACH nombre IN ARRAY ARRAY[""" + nombres + """]
            LOOP
                IF to_regclass('public.' || nombre) IS NULL THEN
                    CONTINUE;
                END IF;

                SELECT a.attname
                  INTO campo_pk
                  FROM pg_index i
                  JOIN pg_attribute a
                    ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
                 WHERE i.indrelid = ('public.' || nombre)::regclass
                   AND i.indisprimary
                 ORDER BY array_position(i.indkey, a.attnum)
                 LIMIT 1;

                IF campo_pk IS NULL THEN
                    RAISE EXCEPTION 'La tabla auxiliar %% no tiene llave primaria', nombre;
                END IF;

                SELECT string_agg(
                           format('%%I %%s', a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod)),
                           ', ' ORDER BY a.attnum
                       )
                  INTO columnas
                  FROM pg_attribute a
                 WHERE a.attrelid = ('public.' || nombre)::regclass
                   AND a.attnum > 0 AND NOT a.attisdropped;

                tipo_fila := '_aux_' || nombre;
                EXECUTE format('DROP TYPE IF EXISTS %%I CASCADE', tipo_fila);
                EXECUTE format('CREATE TYPE %%I AS (%%s)', tipo_fila, columnas);
                EXECUTE format(
                    'INSERT INTO sistema_registro_auxiliar(tipo, clave, datos) '
                    'SELECT %%L, (%%I)::text, to_jsonb(origen) FROM %%I origen '
                    'ON CONFLICT (tipo, clave) DO UPDATE SET datos = EXCLUDED.datos',
                    nombre, campo_pk, nombre
                );
                EXECUTE format('DROP TABLE %%I CASCADE', nombre);
                EXECUTE format(
                    'CREATE VIEW %%I AS '
                    'SELECT (jsonb_populate_record(NULL::%%I, datos)).* '
                    'FROM sistema_registro_auxiliar WHERE tipo = %%L',
                    nombre, tipo_fila, nombre
                );
                EXECUTE format(
                    'CREATE TRIGGER auxiliar_dml INSTEAD OF INSERT OR UPDATE OR DELETE ON %%I '
                    'FOR EACH ROW EXECUTE FUNCTION sistema_registro_auxiliar_dml(%%L)',
                    nombre, campo_pk
                );
            END LOOP;
        END
        $compactar$;
        """
    )


class Migration(migrations.Migration):
    atomic = True
    # sessions debe existir antes de convertirla; evita que Django la cree como
    # una tabla número 11 al preparar una base nueva.
    dependencies = [
        ("hallazgos", "0005_vista_registro_general"),
        ("sessions", "0001_initial"),
    ]
    operations = [migrations.RunPython(compactar, migrations.RunPython.noop)]
