# Generated by Django 5.2.17 on 2026-09-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0007_recrear_registro_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='actividad',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
