# Generated by Django 5.2.17 on 2026-09-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0015_eliminar_tipos_compatibilidad'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.CreateModel(
            name='EventoRegistro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evento',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='RegistroGeneral',
        ),
        migrations.AlterModelOptions(
            name='ciclotratamiento',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='comunicacionhallazgo',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='correlativosac',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='evaluacioneficacia',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['-fecha_registro', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['-fecha_carga']},
        ),
        migrations.AlterModelOptions(
            name='historialhallazgo',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['-fecha_hora', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='pbi',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False},
        ),
        migrations.RenameIndex(
            model_name='hallazgo',
            new_name='registro_ge_estado_f20c3e_idx',
            old_name='hallazgos_h_estado_7a4480_idx',
        ),
        migrations.RenameIndex(
            model_name='hallazgo',
            new_name='registro_ge_respons_f3cac0_idx',
            old_name='hallazgos_h_respons_f759c0_idx',
        ),
        migrations.RenameIndex(
            model_name='hallazgo',
            new_name='registro_ge_proceso_848d4c_idx',
            old_name='hallazgos_h_proceso_3a856a_idx',
        ),
        migrations.AlterModelTable(
            name='accion',
            table='actividad',
        ),
        migrations.AlterModelTable(
            name='hallazgo',
            table='registro_general',
        ),
        ],
    )]
