# Generated by Django 5.2.17 on 2026-09-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0016_eventoregistro_delete_registrogeneral_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.AlterModelTable(
            name='ciclotratamiento',
            table='evento',
        ),
        migrations.AlterModelTable(
            name='comunicacionhallazgo',
            table='evento',
        ),
        migrations.AlterModelTable(
            name='correlativosac',
            table='configuracion',
        ),
        migrations.AlterModelTable(
            name='evaluacioneficacia',
            table='evento',
        ),
        migrations.AlterModelTable(
            name='evidencia',
            table='evento',
        ),
        migrations.AlterModelTable(
            name='historialhallazgo',
            table='evento',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='evento',
        ),
        migrations.AlterModelTable(
            name='pbi',
            table='evento',
        ),
        ],
    )]
