# Generated by Django 5.2.17 on 2026-09-29 03:18

from django.db import migrations, models


def _numero(valor):
    return f"{int(valor):,}"


def completar_snapshots(apps, schema_editor):
    """Congela los rangos vigentes para los hallazgos creados antes de esta migración."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT clientes_bajo_desde, clientes_bajo_hasta,
                   clientes_medio_desde, clientes_medio_hasta, clientes_alto_desde,
                   tiempo_bajo_desde, tiempo_bajo_hasta,
                   tiempo_medio_desde, tiempo_medio_hasta, tiempo_alto_desde,
                   financiero_medio_desde, financiero_alto_desde
              FROM configuracion
             WHERE registro_tipo = 'CONFIGURACION_IMPACTO'
             ORDER BY id
             LIMIT 1
            """
        )
        valores = cursor.fetchone() or (0, 99, 100, 499, 500, 0, 29, 30, 120, 121, 1000000, 2000000)
        (
            cb_d, cb_h, cm_d, cm_h, ca_d,
            tb_d, tb_h, tm_d, tm_h, ta_d,
            fm_d, fa_d,
        ) = valores
        rangos = {
            "clientes": {
                1: f"{_numero(cb_d)} – {_numero(cb_h)} cuentas",
                2: f"{_numero(cm_d)} – {_numero(cm_h)} cuentas",
                3: f"{_numero(ca_d)} o más cuentas",
            },
            "tiempo": {
                1: f"{_numero(tb_d)} – {_numero(tb_h)} min",
                2: f"{_numero(tm_d)} – {_numero(tm_h)} min",
                3: f"{_numero(ta_d)} o más min",
            },
            "financiero": {
                1: f"Menos de S/ {_numero(fm_d)}",
                2: f"S/ {_numero(fm_d)} a menos de S/ {_numero(fa_d)}",
                3: f"S/ {_numero(fa_d)} o más",
            },
        }
        cursor.execute(
            """
            SELECT id, aplica_impacto, impacto_clientes, impacto_tiempo, impacto_soles
              FROM registro_general
            """
        )
        actualizaciones = []
        for hallazgo_id, aplica, clientes, tiempo, financiero in cursor.fetchall():
            if aplica:
                seleccion_clientes = rangos["clientes"].get(clientes, "")
                seleccion_tiempo = rangos["tiempo"].get(tiempo, "")
                seleccion_financiero = rangos["financiero"].get(financiero, "")
            else:
                seleccion_clientes = seleccion_tiempo = seleccion_financiero = ""
            actualizaciones.append((seleccion_clientes, seleccion_tiempo, seleccion_financiero, hallazgo_id))
        cursor.executemany(
            """
            UPDATE registro_general
               SET impacto_clientes_seleccion = %s,
                   impacto_tiempo_seleccion = %s,
                   impacto_financiero_seleccion = %s
             WHERE id = %s
            """,
            actualizaciones,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0017_alter_ciclotratamiento_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='impacto_clientes_seleccion',
            field=models.CharField(blank=True, editable=False, max_length=180),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='impacto_financiero_seleccion',
            field=models.CharField(blank=True, editable=False, max_length=180),
        ),
        migrations.AddField(
            model_name='hallazgo',
            name='impacto_tiempo_seleccion',
            field=models.CharField(blank=True, editable=False, max_length=180),
        ),
        migrations.RunPython(completar_snapshots, migrations.RunPython.noop),
    ]
