# Generated by Django 5.2.17 on 2026-10-06 04:38

import hashlib

import django.db.models.deletion
from django.db import migrations, models


def migrar_archivos_a_postgresql(apps, schema_editor):
    from django.core.files.storage import default_storage

    ArchivoEvidencia = apps.get_model('hallazgos', 'ArchivoEvidencia')
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, archivo, tamanio FROM evento "
            "WHERE registro_tipo = 'EVIDENCIA' ORDER BY id"
        )
        evidencias = cursor.fetchall()
    for evidencia_id, archivo, tamanio in evidencias:
        nombre = str(archivo or '')
        if not nombre:
            raise RuntimeError(f'La evidencia {evidencia_id} no tiene archivo asociado.')
        try:
            with default_storage.open(nombre, 'rb') as origen:
                contenido = origen.read()
        except FileNotFoundError as error:
            raise RuntimeError(
                f'No se encontró el archivo de la evidencia {evidencia_id}: {nombre}'
            ) from error
        if len(contenido) != tamanio:
            raise RuntimeError(
                f'El tamaño de la evidencia {evidencia_id} no coincide: '
                f'{len(contenido)} bytes leídos, {tamanio} registrados.'
            )
        digest = hashlib.sha256(contenido).hexdigest()
        ArchivoEvidencia.objects.update_or_create(
            evidencia_id=evidencia_id,
            defaults={
                'contenido': contenido,
                'sha256': digest,
            },
        )
        extension = nombre.rsplit('.', 1)[-1].lower() if '.' in nombre else 'bin'
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE evento SET archivo = %s WHERE id = %s",
                [f'db/{digest}.{extension}', evidencia_id],
            )


SESIONES_POSTGRESQL = r"""
CREATE TABLE IF NOT EXISTS django_session (
    session_key varchar(40) PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS django_session_expire_date_a5c62663
    ON django_session (expire_date);
"""

REVERTIR_SESIONES = "DROP TABLE IF EXISTS django_session CASCADE;"


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0020_snapshot_urgencia'),
        ('catalogos', '0008_procesovalidador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('evidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_db', to='hallazgos.evidencia')),
            ],
            options={
                'db_table': 'archivo_evidencia',
            },
        ),
        migrations.RunPython(migrar_archivos_a_postgresql, migrations.RunPython.noop),
        migrations.RunSQL(SESIONES_POSTGRESQL, REVERTIR_SESIONES),
    ]
