# Generated by Django 5.2.17 on 2026-10-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0021_archivoevidencia'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.DeleteModel(
            name='EventoRegistro',
        ),
        migrations.AlterModelOptions(
            name='ciclotratamiento',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='comunicacionhallazgo',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='correlativosac',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evaluacioneficacia',
            options={'ordering': ['-fecha_registro', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='evidencia',
            options={'ordering': ['-fecha_carga']},
        ),
        migrations.AlterModelOptions(
            name='historialhallazgo',
            options={'ordering': ['-fecha_hora', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='pbi',
            options={},
        ),
        ],
    )]
