# Generated by Django 5.2.17 on 2026-10-09 18:29

from django.conf import settings
from django.db import migrations, models


def completar_esquema_24_tablas(apps, schema_editor):
    """Separa `evento`, conserva cada PK y deja exactamente 24 tablas físicas."""
    if schema_editor.connection.vendor != 'postgresql':
        raise RuntimeError('La migración de 24 tablas debe ejecutarse primero en PostgreSQL.')
    schema_editor.execute(r"""
        CREATE TABLE correlativo_sac (
            id bigserial PRIMARY KEY,
            anio smallint NOT NULL,
            ambito varchar(10) NOT NULL,
            ultimo_numero integer NOT NULL DEFAULT 0,
            CONSTRAINT correlativo_anio_ambito_unico UNIQUE (anio, ambito)
        );
        INSERT INTO correlativo_sac (id, anio, ambito, ultimo_numero)
        SELECT id, anio, ambito, ultimo_numero
          FROM configuracion WHERE registro_tipo = 'CORRELATIVO_SAC';

        CREATE TABLE ciclo_tratamiento (
            id bigserial PRIMARY KEY,
            hallazgo_id bigint NOT NULL REFERENCES registro_general(id) ON DELETE RESTRICT,
            numero integer NOT NULL,
            motivo text NOT NULL,
            creado_por_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
            fecha_inicio timestamptz NOT NULL,
            fecha_fin timestamptz,
            analisis_responsable_id bigint REFERENCES usuario(id) ON DELETE RESTRICT,
            analisis_inicio timestamptz,
            analisis_fin timestamptz,
            causa_raiz text NOT NULL DEFAULT '',
            checklist_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
            respuestas jsonb NOT NULL DEFAULT '[]'::jsonb,
            control jsonb NOT NULL DEFAULT '{}'::jsonb,
            responsable_cierre_id bigint REFERENCES usuario(id) ON DELETE RESTRICT,
            fecha_cierre timestamptz,
            comentarios_cierre text NOT NULL DEFAULT '',
            resultado_cierre varchar(12) NOT NULL DEFAULT '',
            CONSTRAINT ciclo_hallazgo_numero_unico UNIQUE (hallazgo_id, numero)
        );
        INSERT INTO ciclo_tratamiento
            (id, hallazgo_id, numero, motivo, creado_por_id, fecha_inicio, fecha_fin,
             analisis_responsable_id, analisis_inicio, analisis_fin, causa_raiz,
             checklist_snapshot, respuestas, control, responsable_cierre_id,
             fecha_cierre, comentarios_cierre, resultado_cierre)
        SELECT id, hallazgo_id, numero, motivo, creado_por_id, fecha_inicio, fecha_fin,
               analisis_responsable_id, analisis_inicio, analisis_fin, COALESCE(causa_raiz, ''),
               COALESCE(checklist_snapshot, '[]'::jsonb), COALESCE(respuestas, '[]'::jsonb),
               COALESCE(control, '{}'::jsonb), responsable_cierre_id,
               fecha_cierre, COALESCE(comentarios_cierre, ''), COALESCE(resultado_cierre, '')
          FROM evento WHERE registro_tipo = 'CICLO_TRATAMIENTO';

        CREATE TABLE pbi (
            id bigserial PRIMARY KEY,
            ciclo_id bigint NOT NULL REFERENCES ciclo_tratamiento(id) ON DELETE RESTRICT,
            numero_pbi varchar(100) NOT NULL,
            ticket_incidente varchar(100) NOT NULL DEFAULT '',
            sistema varchar(200) NOT NULL,
            herramienta varchar(100) NOT NULL DEFAULT 'Helix (registro manual)',
            responsable_ti_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
            estado varchar(10) NOT NULL DEFAULT 'ABIERTO',
            fecha_creacion timestamptz NOT NULL,
            fecha_cierre_pbi date,
            observacion text NOT NULL DEFAULT '',
            CONSTRAINT pbi_ciclo_numero_unico UNIQUE (ciclo_id, numero_pbi)
        );
        INSERT INTO pbi
            (id, ciclo_id, numero_pbi, ticket_incidente, sistema, herramienta,
             responsable_ti_id, estado, fecha_creacion, fecha_cierre_pbi, observacion)
        SELECT id, ciclo_id, numero_pbi, COALESCE(ticket_incidente, ''), sistema, herramienta,
               responsable_ti_id, estado, fecha_creacion, fecha_cierre_pbi, COALESCE(observacion, '')
          FROM evento WHERE registro_tipo = 'PBI';

        CREATE TABLE evaluacion_eficacia (
            id bigserial PRIMARY KEY,
            ciclo_id bigint NOT NULL REFERENCES ciclo_tratamiento(id) ON DELETE RESTRICT,
            evaluador_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
            fecha_evaluacion date NOT NULL,
            resultado varchar(12) NOT NULL,
            comentario text NOT NULL,
            fecha_registro timestamptz NOT NULL,
            CONSTRAINT evaluacion_resultado_valido CHECK (resultado IN ('EFICAZ', 'NO_EFICAZ'))
        );
        INSERT INTO evaluacion_eficacia
            (id, ciclo_id, evaluador_id, fecha_evaluacion, resultado, comentario, fecha_registro)
        SELECT id, ciclo_id, evaluador_id, fecha_evaluacion, resultado, comentario, fecha_registro
          FROM evento WHERE registro_tipo = 'EVALUACION_EFICACIA';

        CREATE TABLE comunicacion (
            id bigserial PRIMARY KEY,
            ciclo_id bigint NOT NULL REFERENCES ciclo_tratamiento(id) ON DELETE RESTRICT,
            registrado_por_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
            destinatarios varchar(500) NOT NULL,
            medio varchar(120) NOT NULL,
            descripcion text NOT NULL,
            fecha timestamptz NOT NULL
        );
        INSERT INTO comunicacion
            (id, ciclo_id, registrado_por_id, destinatarios, medio, descripcion, fecha)
        SELECT id, ciclo_id, registrado_por_id, destinatarios, medio, descripcion, fecha
          FROM evento WHERE registro_tipo = 'COMUNICACION';

        CREATE TABLE evidencia (
            id bigserial PRIMARY KEY,
            hallazgo_id bigint NOT NULL REFERENCES registro_general(id) ON DELETE RESTRICT,
            accion_id bigint REFERENCES actividad(id) ON DELETE RESTRICT,
            analisis_id bigint REFERENCES ciclo_tratamiento(id) ON DELETE RESTRICT,
            evaluacion_id bigint REFERENCES evaluacion_eficacia(id) ON DELETE RESTRICT,
            cierre_id bigint REFERENCES ciclo_tratamiento(id) ON DELETE RESTRICT,
            archivo varchar(100) NOT NULL,
            nombre_original varchar(255) NOT NULL,
            mime_type varchar(100) NOT NULL,
            tamanio integer NOT NULL,
            subido_por_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
            fecha_carga timestamptz NOT NULL,
            descripcion text NOT NULL DEFAULT '',
            CONSTRAINT evidencia_tamanio_positivo CHECK (tamanio > 0)
        );
        INSERT INTO evidencia
            (id, hallazgo_id, accion_id, analisis_id, evaluacion_id, cierre_id,
             archivo, nombre_original, mime_type, tamanio, subido_por_id, fecha_carga, descripcion)
        SELECT id, hallazgo_id, accion_id, analisis_id, evaluacion_id, cierre_id,
               archivo, nombre_original, mime_type, tamanio, subido_por_id, fecha_carga,
               COALESCE(descripcion, '')
          FROM evento WHERE registro_tipo = 'EVIDENCIA';

        CREATE TABLE historial_hallazgo (
            id bigserial PRIMARY KEY,
            accion_relacionada_id bigint REFERENCES actividad(id) ON DELETE RESTRICT,
            hallazgo_id bigint NOT NULL REFERENCES registro_general(id) ON DELETE RESTRICT,
            usuario_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
            fecha_hora timestamptz NOT NULL,
            accion varchar(70) NOT NULL,
            estado_anterior varchar(30) NOT NULL DEFAULT '',
            estado_nuevo varchar(30) NOT NULL DEFAULT '',
            comentario text NOT NULL DEFAULT '',
            metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb
        );
        INSERT INTO historial_hallazgo
            (id, accion_relacionada_id, hallazgo_id, usuario_id, fecha_hora, accion,
             estado_anterior, estado_nuevo, comentario, metadata_json)
        SELECT id, accion_relacionada_id, hallazgo_id, usuario_id, fecha_hora, accion,
               COALESCE(estado_anterior, ''), COALESCE(estado_nuevo, ''),
               COALESCE(comentario, ''), COALESCE(metadata_json, '{}'::jsonb)
          FROM evento WHERE registro_tipo = 'HISTORIAL';

        CREATE TABLE notificacion (
            id bigserial PRIMARY KEY,
            usuario_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
            hallazgo_id bigint NOT NULL REFERENCES registro_general(id) ON DELETE RESTRICT,
            tipo varchar(50) NOT NULL,
            titulo varchar(250) NOT NULL,
            mensaje text NOT NULL,
            leida boolean NOT NULL DEFAULT false,
            fecha_creacion timestamptz NOT NULL,
            fecha_lectura timestamptz
        );
        INSERT INTO notificacion
            (id, usuario_id, hallazgo_id, tipo, titulo, mensaje, leida, fecha_creacion, fecha_lectura)
        SELECT id, usuario_id, hallazgo_id, tipo, titulo, mensaje, leida, fecha_creacion, fecha_lectura
          FROM evento WHERE registro_tipo = 'NOTIFICACION';

        INSERT INTO auditoria_administracion
            (id, usuario_id, fecha, entidad, objeto, accion, antes, despues)
        SELECT id, usuario_id, fecha, entidad, objeto, accion,
               COALESCE(antes, '{}'::jsonb), COALESCE(despues, '{}'::jsonb)
          FROM evento WHERE registro_tipo = 'AUDITORIA_ADMINISTRACION';

        DO $$
        DECLARE tipo_evento text; esperado bigint; migrado bigint;
        BEGIN
          FOREACH tipo_evento IN ARRAY ARRAY['CICLO_TRATAMIENTO','PBI','EVALUACION_EFICACIA','COMUNICACION','EVIDENCIA','HISTORIAL','NOTIFICACION','AUDITORIA_ADMINISTRACION']
          LOOP
            SELECT count(*) INTO esperado FROM evento WHERE registro_tipo = tipo_evento;
            EXECUTE format('SELECT count(*) FROM %%I', CASE tipo_evento
              WHEN 'CICLO_TRATAMIENTO' THEN 'ciclo_tratamiento'
              WHEN 'EVALUACION_EFICACIA' THEN 'evaluacion_eficacia'
              WHEN 'HISTORIAL' THEN 'historial_hallazgo'
              WHEN 'AUDITORIA_ADMINISTRACION' THEN 'auditoria_administracion'
              ELSE lower(tipo_evento) END) INTO migrado;
            IF esperado <> migrado THEN
              RAISE EXCEPTION 'Migración incompleta para %%: %% de %% filas', tipo_evento, migrado, esperado;
            END IF;
          END LOOP;
        END $$;

        DROP TRIGGER IF EXISTS proceso_validadores_insertar ON configuracion;
        DROP TRIGGER IF EXISTS proceso_validadores_actualizar ON configuracion;
        DROP FUNCTION IF EXISTS portal_sincronizar_proceso_validadores();

        DO $$ DECLARE r record; BEGIN
          FOR r IN
            SELECT conrelid::regclass AS tabla, conname
              FROM pg_constraint
             WHERE contype = 'f'
               AND confrelid IN ('configuracion'::regclass, 'evento'::regclass)
          LOOP
            EXECUTE format('ALTER TABLE %%s DROP CONSTRAINT %%I', r.tabla, r.conname);
          END LOOP;
        END $$;

        ALTER TABLE registro_general ADD CONSTRAINT registro_tipo_fk
          FOREIGN KEY (tipo_registro_id) REFERENCES catalogo(id) DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE registro_general ADD CONSTRAINT registro_fuente_fk
          FOREIGN KEY (fuente_deteccion_id) REFERENCES catalogo(id) DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE registro_general ADD CONSTRAINT registro_proceso_fk
          FOREIGN KEY (proceso_id) REFERENCES proceso(id) DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE registro_general ADD CONSTRAINT registro_subproceso_fk
          FOREIGN KEY (subproceso_id) REFERENCES subproceso(id) DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE registro_general ADD CONSTRAINT registro_urgencia_fk
          FOREIGN KEY (urgencia_id) REFERENCES catalogo(id) DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE registro_general ADD CONSTRAINT registro_prioridad_fk
          FOREIGN KEY (prioridad_id) REFERENCES catalogo(id) DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE actividad ADD CONSTRAINT actividad_ciclo_fk
          FOREIGN KEY (ciclo_id) REFERENCES ciclo_tratamiento(id) DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE proceso_validador ADD CONSTRAINT proceso_validador_proceso_fk
          FOREIGN KEY (proceso_id) REFERENCES proceso(id) ON DELETE CASCADE;
        ALTER TABLE archivo_evidencia ADD CONSTRAINT archivo_evidencia_evidencia_fk
          FOREIGN KEY (evidencia_id) REFERENCES evidencia(id) ON DELETE CASCADE;

        CREATE OR REPLACE FUNCTION portal_sincronizar_proceso_validadores()
        RETURNS trigger AS $$
        BEGIN
          DELETE FROM proceso_validador WHERE proceso_id = NEW.id;
          INSERT INTO proceso_validador (proceso_id, usuario_id)
          SELECT NEW.id, valores.usuario_id::bigint
            FROM jsonb_array_elements_text(COALESCE(NEW.validadores_ids, '[]'::jsonb)) AS valores(usuario_id)
            JOIN usuario u ON u.id = valores.usuario_id::bigint
          ON CONFLICT (proceso_id, usuario_id) DO NOTHING;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER proceso_validadores_insertar
          AFTER INSERT ON proceso FOR EACH ROW EXECUTE FUNCTION portal_sincronizar_proceso_validadores();
        CREATE TRIGGER proceso_validadores_actualizar
          AFTER UPDATE OF validadores_ids ON proceso FOR EACH ROW EXECUTE FUNCTION portal_sincronizar_proceso_validadores();

        CREATE INDEX ciclo_hallazgo_idx ON ciclo_tratamiento(hallazgo_id);
        CREATE INDEX pbi_ciclo_idx ON pbi(ciclo_id);
        CREATE INDEX evaluacion_ciclo_idx ON evaluacion_eficacia(ciclo_id);
        CREATE INDEX comunicacion_ciclo_idx ON comunicacion(ciclo_id);
        CREATE INDEX evidencia_hallazgo_idx ON evidencia(hallazgo_id);
        CREATE INDEX historial_hallazgo_fecha_idx ON historial_hallazgo(hallazgo_id, fecha_hora DESC);
        CREATE INDEX notif_usuario_estado_idx ON notificacion(usuario_id, leida, fecha_creacion DESC);

        SELECT setval(pg_get_serial_sequence('correlativo_sac','id'), GREATEST(COALESCE((SELECT MAX(id) FROM correlativo_sac), 1), 1));
        SELECT setval(pg_get_serial_sequence('ciclo_tratamiento','id'), GREATEST(COALESCE((SELECT MAX(id) FROM ciclo_tratamiento), 1), 1));
        SELECT setval(pg_get_serial_sequence('pbi','id'), GREATEST(COALESCE((SELECT MAX(id) FROM pbi), 1), 1));
        SELECT setval(pg_get_serial_sequence('evaluacion_eficacia','id'), GREATEST(COALESCE((SELECT MAX(id) FROM evaluacion_eficacia), 1), 1));
        SELECT setval(pg_get_serial_sequence('comunicacion','id'), GREATEST(COALESCE((SELECT MAX(id) FROM comunicacion), 1), 1));
        SELECT setval(pg_get_serial_sequence('evidencia','id'), GREATEST(COALESCE((SELECT MAX(id) FROM evidencia), 1), 1));
        SELECT setval(pg_get_serial_sequence('historial_hallazgo','id'), GREATEST(COALESCE((SELECT MAX(id) FROM historial_hallazgo), 1), 1));
        SELECT setval(pg_get_serial_sequence('notificacion','id'), GREATEST(COALESCE((SELECT MAX(id) FROM notificacion), 1), 1));
        SELECT setval(pg_get_serial_sequence('auditoria_administracion','id'), GREATEST(COALESCE((SELECT MAX(id) FROM auditoria_administracion), 1), 1));

        DROP TABLE evento;
        DROP TABLE configuracion;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0022_delete_eventoregistro_alter_ciclotratamiento_options_and_more'),
        ('catalogos', '0010_remove_catalogo_catalogo_clase_valor_unico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    state_operations = [
        migrations.RemoveConstraint(
            model_name='correlativosac',
            name='sac_anio_ambito_unico',
        ),
        migrations.RemoveConstraint(
            model_name='evaluacioneficacia',
            name='eficacia_resultado_valido',
        ),
        migrations.RemoveConstraint(
            model_name='pbi',
            name='pbi_referencia_ciclo_unico',
        ),
        migrations.RemoveConstraint(
            model_name='pbi',
            name='pbi_cierre_coherente',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notif_usuario_estado_idx',
            old_name='hallazgos_n_usuario_f00322_idx',
        ),
        migrations.AlterField(
            model_name='ciclotratamiento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comunicacionhallazgo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='correlativosac',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluacioneficacia',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historialhallazgo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='fecha_cierre',
            field=models.DateField(blank=True, db_column='fecha_cierre_pbi', null=True),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='correlativosac',
            constraint=models.UniqueConstraint(fields=('anio', 'ambito'), name='correlativo_anio_ambito_unico'),
        ),
        migrations.AddConstraint(
            model_name='pbi',
            constraint=models.UniqueConstraint(fields=('ciclo', 'numero_pbi'), name='pbi_ciclo_numero_unico'),
        ),
        migrations.AlterModelTable(
            name='ciclotratamiento',
            table='ciclo_tratamiento',
        ),
        migrations.AlterModelTable(
            name='comunicacionhallazgo',
            table='comunicacion',
        ),
        migrations.AlterModelTable(
            name='correlativosac',
            table='correlativo_sac',
        ),
        migrations.AlterModelTable(
            name='evaluacioneficacia',
            table='evaluacion_eficacia',
        ),
        migrations.AlterModelTable(
            name='evidencia',
            table='evidencia',
        ),
        migrations.AlterModelTable(
            name='historialhallazgo',
            table='historial_hallazgo',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificacion',
        ),
        migrations.AlterModelTable(
            name='pbi',
            table='pbi',
        ),
    ]
    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[migrations.RunPython(completar_esquema_24_tablas, migrations.RunPython.noop)],
        state_operations=state_operations,
    )]
