# Generated by Django 5.2.17 on 2026-10-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallazgos', '0023_remove_correlativosac_sac_anio_ambito_unico_and_more'),
        ('catalogos', '0011_alter_auditoriaadministracion_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accion',
            table='tbl_actividad_nc',
        ),
        migrations.AlterModelTable(
            name='archivoevidencia',
            table='tbl_archivo_evidencia_nc',
        ),
        migrations.AlterModelTable(
            name='ciclotratamiento',
            table='tbl_ciclo_tratamiento_nc',
        ),
        migrations.AlterModelTable(
            name='comunicacionhallazgo',
            table='tbl_comunicacion_nc',
        ),
        migrations.AlterModelTable(
            name='correlativosac',
            table='tbl_correlativo_sac_nc',
        ),
        migrations.AlterModelTable(
            name='evaluacioneficacia',
            table='tbl_evaluacion_eficacia_nc',
        ),
        migrations.AlterModelTable(
            name='evidencia',
            table='tbl_evidencia_nc',
        ),
        migrations.AlterModelTable(
            name='hallazgo',
            table='tbl_registro_general_nc',
        ),
        migrations.AlterModelTable(
            name='historialhallazgo',
            table='tbl_historial_hallazgo_nc',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='tbl_notificacion_nc',
        ),
        migrations.AlterModelTable(
            name='pbi',
            table='tbl_pbi_nc',
        ),
    ]
