# Generated by Django 5.2.17 on 2026-09-22 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCausa',
            fields=[
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EstadoHallazgo',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FuenteDeteccion',
            fields=[
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entidad', models.CharField(max_length=100)),
                ('objeto', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=40)),
                ('antes', models.JSONField(default=dict)),
                ('despues', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Impacto',
            fields=[
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('valor', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['valor'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 1), ('valor__lte', 3)), name='impacto_nivel_valido')],
            },
        ),
        migrations.CreateModel(
            name='PreguntaCausa',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('orden', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='catalogos.categoriacausa')),
            ],
            options={
                'ordering': ['categoria__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos_responsables', to=settings.AUTH_USER_MODEL)),
                ('validadores', models.ManyToManyField(blank=True, related_name='procesos_validacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('valor', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['valor'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gte', 1), ('valor__lte', 3)), name='urgencia_nivel_valido')],
            },
        ),
        migrations.CreateModel(
            name='Subproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subprocesos', to='catalogos.proceso')),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('proceso', 'nombre'), name='subproceso_nombre_unico')],
            },
        ),
        migrations.CreateModel(
            name='MatrizPrioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('es_demo', models.BooleanField(default=True)),
                ('impacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.impacto')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.prioridad')),
                ('urgencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.urgencia')),
            ],
            options={
                'ordering': ['impacto_id', 'urgencia_id'],
                'constraints': [models.UniqueConstraint(fields=('impacto', 'urgencia'), name='matriz_prioridad_combinacion_unica')],
            },
        ),
    ]
