# Generated by Django 5.2.17 on 2026-09-22 15:35

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models


def consolidar_catalogos(apps, schema_editor):
    alias = schema_editor.connection.alias
    Catalogo = apps.get_model("catalogos", "Catalogo")
    mapas = {}
    for modelo, clase in [("TipoRegistro", "TIPO"), ("FuenteDeteccion", "FUENTE"), ("Impacto", "IMPACTO"), ("Urgencia", "URGENCIA"), ("Prioridad", "PRIORIDAD"), ("CategoriaCausa", "CATEGORIA")]:
        mapas[clase] = {}
        for viejo in apps.get_model("catalogos", modelo).objects.using(alias).all():
            nuevo = Catalogo.objects.using(alias).create(clase=clase, codigo=str(viejo.pk), nombre=viejo.nombre, activo=viejo.activo, valor=viejo.pk if clase in {"IMPACTO", "URGENCIA"} else None, orden=getattr(viejo, "orden", 0))
            mapas[clase][viejo.pk] = nuevo.pk
    for row in apps.get_model("catalogos", "MatrizPrioridad").objects.using(alias).all():
        row.impacto_nuevo_id = mapas["IMPACTO"][row.impacto_id]
        row.urgencia_nuevo_id = mapas["URGENCIA"][row.urgencia_id]
        row.prioridad_nuevo_id = mapas["PRIORIDAD"][row.prioridad_id]
        row.save(using=alias, update_fields=["impacto_nuevo", "urgencia_nuevo", "prioridad_nuevo"])
    for row in apps.get_model("catalogos", "PreguntaCausa").objects.using(alias).all():
        row.categoria_nueva_id = mapas["CATEGORIA"][row.categoria_id]
        row.save(using=alias, update_fields=["categoria_nueva"])

    # Flush deferred foreign-key checks before the following schema changes.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('hallazgos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(choices=[('TIPO', 'Tipo de hallazgo'), ('FUENTE', 'Fuente'), ('IMPACTO', 'Impacto'), ('URGENCIA', 'Urgencia'), ('PRIORIDAD', 'Prioridad'), ('CATEGORIA', 'Categoría 6M')], max_length=12)),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('valor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('clase', 'codigo'), name='catalogo_clase_codigo_unico'), models.UniqueConstraint(fields=('clase', 'valor'), name='catalogo_clase_valor_unico'), models.CheckConstraint(condition=models.Q(models.Q(('clase__in', ['IMPACTO', 'URGENCIA']), _negated=True), models.Q(('valor__isnull', False), ('valor__range', (1, 3))), _connector='OR'), name='catalogo_nivel_valido')],
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='proceso',
            name='gerencia',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='matrizprioridad',
            name='impacto_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.AddField(
            model_name='matrizprioridad',
            name='urgencia_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.AddField(
            model_name='matrizprioridad',
            name='prioridad_nuevo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.AddField(
            model_name='preguntacausa',
            name='categoria_nueva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.RunPython(
            code=consolidar_catalogos,
        ),
        migrations.RemoveConstraint(
            model_name='matrizprioridad',
            name='matriz_prioridad_combinacion_unica',
        ),
        migrations.RemoveField(
            model_name='matrizprioridad',
            name='impacto',
        ),
        migrations.RenameField(
            model_name='matrizprioridad',
            old_name='impacto_nuevo',
            new_name='impacto',
        ),
        migrations.AlterField(
            model_name='matrizprioridad',
            name='impacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.RemoveField(
            model_name='matrizprioridad',
            name='urgencia',
        ),
        migrations.RenameField(
            model_name='matrizprioridad',
            old_name='urgencia_nuevo',
            new_name='urgencia',
        ),
        migrations.AlterField(
            model_name='matrizprioridad',
            name='urgencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.RemoveField(
            model_name='matrizprioridad',
            name='prioridad',
        ),
        migrations.RenameField(
            model_name='matrizprioridad',
            old_name='prioridad_nuevo',
            new_name='prioridad',
        ),
        migrations.AlterField(
            model_name='matrizprioridad',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.catalogo'),
        ),
        migrations.RemoveField(
            model_name='preguntacausa',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='preguntacausa',
            old_name='categoria_nueva',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='preguntacausa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='catalogos.catalogo'),
        ),
        migrations.AddConstraint(
            model_name='matrizprioridad',
            constraint=models.UniqueConstraint(fields=('impacto', 'urgencia'), name='matriz_prioridad_combinacion_unica'),
        ),
    ]
