# Generated by Django 5.2.17 on 2026-09-22 15:35

import apps.catalogos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_catalogo_unificado'),
        ('hallazgos', '0002_tratamiento_compacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoRegistro',
        ),
        migrations.DeleteModel(
            name='FuenteDeteccion',
        ),
        migrations.DeleteModel(
            name='Impacto',
        ),
        migrations.DeleteModel(
            name='Urgencia',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
        migrations.DeleteModel(
            name='CategoriaCausa',
        ),
        migrations.DeleteModel(
            name='EstadoHallazgo',
        ),
        migrations.CreateModel(
            name='TipoRegistro',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.catalogos.models.CatalogoTipado, 'catalogos.catalogo'),
        ),
        migrations.CreateModel(
            name='FuenteDeteccion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.catalogos.models.CatalogoTipado, 'catalogos.catalogo'),
        ),
        migrations.CreateModel(
            name='Impacto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.catalogos.models.CatalogoTipado, 'catalogos.catalogo'),
        ),
        migrations.CreateModel(
            name='Urgencia',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.catalogos.models.CatalogoTipado, 'catalogos.catalogo'),
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.catalogos.models.CatalogoTipado, 'catalogos.catalogo'),
        ),
        migrations.CreateModel(
            name='CategoriaCausa',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.catalogos.models.CatalogoTipado, 'catalogos.catalogo'),
        ),
        migrations.AlterField(
            model_name='matrizprioridad',
            name='impacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.impacto'),
        ),
        migrations.AlterField(
            model_name='matrizprioridad',
            name='urgencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.urgencia'),
        ),
        migrations.AlterField(
            model_name='matrizprioridad',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogos.prioridad'),
        ),
        migrations.AlterField(
            model_name='preguntacausa',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='catalogos.categoriacausa'),
        ),
    ]
