# Generated by Django 5.2.17 on 2026-09-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_configuracionimpacto'),
        ('hallazgos', '0015_eliminar_tipos_compatibilidad'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.CreateModel(
            name='ConfiguracionRegistro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'configuracion',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='auditoriaadministracion',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['-fecha', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['orden', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='configuracionimpacto',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'verbose_name': 'configuración de impacto', 'verbose_name_plural': 'configuración de impacto'},
        ),
        migrations.AlterModelOptions(
            name='matrizprioridad',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['impacto_id', 'urgencia_id']},
        ),
        migrations.AlterModelOptions(
            name='preguntacausa',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['categoria__orden', 'orden']},
        ),
        migrations.AlterModelOptions(
            name='proceso',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='subproceso',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'managed': False, 'ordering': ['nombre']},
        ),
        ],
    )]
