# Generated by Django 5.2.17 on 2026-09-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_configuracionregistro_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.AlterModelTable(
            name='auditoriaadministracion',
            table='evento',
        ),
        migrations.AlterModelTable(
            name='catalogo',
            table='configuracion',
        ),
        migrations.AlterModelTable(
            name='configuracionimpacto',
            table='configuracion',
        ),
        migrations.AlterModelTable(
            name='matrizprioridad',
            table='configuracion',
        ),
        migrations.AlterModelTable(
            name='preguntacausa',
            table='configuracion',
        ),
        migrations.AlterModelTable(
            name='proceso',
            table='configuracion',
        ),
        migrations.AlterModelTable(
            name='subproceso',
            table='configuracion',
        ),
        ],
    )]
