# Generated by Django 5.2.17 on 2026-10-06 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


SINCRONIZAR_VALIDADORES = r"""
INSERT INTO proceso_validador (proceso_id, usuario_id)
SELECT c.id, validadores.usuario_id::bigint
  FROM configuracion c
 CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(c.validadores_ids, '[]'::jsonb)) AS validadores(usuario_id)
  JOIN usuario u ON u.id = validadores.usuario_id::bigint
 WHERE c.registro_tipo = 'PROCESO'
ON CONFLICT (proceso_id, usuario_id) DO NOTHING;

CREATE OR REPLACE FUNCTION portal_sincronizar_proceso_validadores()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.registro_tipo = 'PROCESO' THEN
        DELETE FROM proceso_validador WHERE proceso_id = OLD.id;
    END IF;
    IF NEW.registro_tipo = 'PROCESO' THEN
        DELETE FROM proceso_validador WHERE proceso_id = NEW.id;
        INSERT INTO proceso_validador (proceso_id, usuario_id)
        SELECT NEW.id, validadores.usuario_id::bigint
          FROM jsonb_array_elements_text(COALESCE(NEW.validadores_ids, '[]'::jsonb)) AS validadores(usuario_id)
          JOIN usuario u ON u.id = validadores.usuario_id::bigint
        ON CONFLICT (proceso_id, usuario_id) DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER proceso_validadores_insertar
AFTER INSERT ON configuracion
FOR EACH ROW EXECUTE FUNCTION portal_sincronizar_proceso_validadores();

CREATE TRIGGER proceso_validadores_actualizar
AFTER UPDATE OF validadores_ids, registro_tipo ON configuracion
FOR EACH ROW EXECUTE FUNCTION portal_sincronizar_proceso_validadores();
"""

REVERTIR_VALIDADORES = r"""
DROP TRIGGER IF EXISTS proceso_validadores_insertar ON configuracion;
DROP TRIGGER IF EXISTS proceso_validadores_actualizar ON configuracion;
DROP FUNCTION IF EXISTS portal_sincronizar_proceso_validadores();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_configuracionurgencia'),
        ('accounts', '0005_usuariorol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoValidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_validacion', to='catalogos.proceso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_proceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proceso_validador',
                'ordering': ['proceso_id', 'usuario_id'],
                'constraints': [models.UniqueConstraint(fields=('proceso', 'usuario'), name='proceso_validador_unico')],
            },
        ),
        migrations.RunSQL(SINCRONIZAR_VALIDADORES, REVERTIR_VALIDADORES),
    ]
