# Generated by Django 5.2.17 on 2026-10-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_procesovalidador'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.DeleteModel(
            name='ConfiguracionRegistro',
        ),
        migrations.AlterModelOptions(
            name='auditoriaadministracion',
            options={'ordering': ['-fecha', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='configuracionimpacto',
            options={'verbose_name': 'configuración de impacto', 'verbose_name_plural': 'configuración de impacto'},
        ),
        migrations.AlterModelOptions(
            name='configuracionurgencia',
            options={'ordering': ['codigo']},
        ),
        migrations.AlterModelOptions(
            name='matrizprioridad',
            options={'ordering': ['impacto_id', 'urgencia_id']},
        ),
        migrations.AlterModelOptions(
            name='preguntacausa',
            options={'ordering': ['categoria__orden', 'orden']},
        ),
        migrations.AlterModelOptions(
            name='proceso',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='subproceso',
            options={'ordering': ['nombre']},
        ),
        ],
    )]
