# Generated by Django 5.2.17 on 2026-10-09 18:29

from django.conf import settings
from django.db import migrations, models


def crear_tablas_normalizadas(apps, schema_editor):
    """Separa `configuracion` sin cambiar los identificadores históricos."""
    if schema_editor.connection.vendor != 'postgresql':
        raise RuntimeError('La migración de 24 tablas debe ejecutarse primero en PostgreSQL.')
    schema_editor.execute(r"""
        CREATE TABLE catalogo (
            id bigserial PRIMARY KEY,
            clase varchar(12) NOT NULL,
            codigo varchar(30) NOT NULL,
            nombre varchar(180) NOT NULL,
            activo boolean NOT NULL DEFAULT true,
            valor smallint,
            orden smallint NOT NULL DEFAULT 0,
            CONSTRAINT catalogo_clase_codigo_unico UNIQUE (clase, codigo)
        );
        CREATE UNIQUE INDEX catalogo_clase_valor_unico
            ON catalogo (clase, valor) WHERE valor IS NOT NULL;
        INSERT INTO catalogo (id, clase, codigo, nombre, activo, valor, orden)
        SELECT id, clase, codigo, nombre, activo, valor, orden
          FROM configuracion WHERE registro_tipo = 'CATALOGO';

        CREATE TABLE proceso (
            id bigserial PRIMARY KEY,
            nombre varchar(180) NOT NULL,
            activo boolean NOT NULL DEFAULT true,
            gerencia varchar(180) NOT NULL DEFAULT '',
            responsable_id bigint REFERENCES usuario(id) ON DELETE RESTRICT,
            validadores_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
            CONSTRAINT proceso_nombre_unico UNIQUE (nombre)
        );
        INSERT INTO proceso (id, nombre, activo, gerencia, responsable_id, validadores_ids)
        SELECT id, nombre, activo, COALESCE(gerencia, ''), responsable_id,
               COALESCE(validadores_ids, '[]'::jsonb)
          FROM configuracion WHERE registro_tipo = 'PROCESO';

        CREATE TABLE subproceso (
            id bigserial PRIMARY KEY,
            proceso_id bigint NOT NULL REFERENCES proceso(id) ON DELETE RESTRICT,
            nombre varchar(180) NOT NULL,
            activo boolean NOT NULL DEFAULT true,
            CONSTRAINT subproceso_proceso_nombre_unico UNIQUE (proceso_id, nombre)
        );
        INSERT INTO subproceso (id, proceso_id, nombre, activo)
        SELECT id, proceso_id, nombre, activo
          FROM configuracion WHERE registro_tipo = 'SUBPROCESO';

        CREATE TABLE matriz_prioridad (
            id bigserial PRIMARY KEY,
            impacto_id bigint NOT NULL REFERENCES catalogo(id) ON DELETE RESTRICT,
            urgencia_id bigint NOT NULL REFERENCES catalogo(id) ON DELETE RESTRICT,
            prioridad_id bigint NOT NULL REFERENCES catalogo(id) ON DELETE RESTRICT,
            activo boolean NOT NULL DEFAULT true,
            es_demo boolean NOT NULL DEFAULT true,
            CONSTRAINT matriz_prioridad_combinacion_unica UNIQUE (impacto_id, urgencia_id)
        );
        INSERT INTO matriz_prioridad (id, impacto_id, urgencia_id, prioridad_id, activo, es_demo)
        SELECT id, impacto_id, urgencia_id, prioridad_id, activo, es_demo
          FROM configuracion WHERE registro_tipo = 'MATRIZ_PRIORIDAD';

        CREATE TABLE configuracion_impacto (
            id bigserial PRIMARY KEY,
            predeterminada boolean NOT NULL DEFAULT true,
            clientes_bajo_desde bigint NOT NULL,
            clientes_bajo_hasta bigint NOT NULL,
            clientes_medio_desde bigint NOT NULL,
            clientes_medio_hasta bigint NOT NULL,
            clientes_alto_desde bigint NOT NULL,
            tiempo_bajo_desde integer NOT NULL,
            tiempo_bajo_hasta integer NOT NULL,
            tiempo_medio_desde integer NOT NULL,
            tiempo_medio_hasta integer NOT NULL,
            tiempo_alto_desde integer NOT NULL,
            financiero_bajo_desde numeric(14,0) NOT NULL,
            financiero_bajo_hasta numeric(14,0) NOT NULL,
            financiero_medio_desde numeric(14,0) NOT NULL,
            financiero_medio_hasta numeric(14,0) NOT NULL,
            financiero_alto_desde numeric(14,0) NOT NULL
        );
        INSERT INTO configuracion_impacto
        SELECT id, predeterminada,
               clientes_bajo_desde, clientes_bajo_hasta,
               clientes_medio_desde, clientes_medio_hasta, clientes_alto_desde,
               tiempo_bajo_desde, tiempo_bajo_hasta,
               tiempo_medio_desde, tiempo_medio_hasta, tiempo_alto_desde,
               financiero_bajo_desde, financiero_bajo_hasta,
               financiero_medio_desde, financiero_medio_hasta, financiero_alto_desde
          FROM configuracion WHERE registro_tipo = 'CONFIGURACION_IMPACTO';

        CREATE TABLE configuracion_urgencia (
            id bigserial PRIMARY KEY,
            codigo varchar(30) NOT NULL,
            nombre varchar(180) NOT NULL,
            activo boolean NOT NULL DEFAULT true,
            tiempo_bajo_desde integer NOT NULL,
            tiempo_bajo_hasta integer NOT NULL,
            tiempo_medio_desde integer NOT NULL,
            tiempo_medio_hasta integer NOT NULL,
            tiempo_alto_desde integer NOT NULL,
            CONSTRAINT configuracion_urgencia_codigo_unico UNIQUE (codigo)
        );
        INSERT INTO configuracion_urgencia
            (id, codigo, nombre, activo, tiempo_bajo_desde, tiempo_bajo_hasta,
             tiempo_medio_desde, tiempo_medio_hasta, tiempo_alto_desde)
        SELECT id, codigo, nombre, activo, tiempo_bajo_desde, tiempo_bajo_hasta,
               tiempo_medio_desde, tiempo_medio_hasta, tiempo_alto_desde
          FROM configuracion WHERE registro_tipo = 'CONFIGURACION_URGENCIA';

        CREATE TABLE pregunta_causa (
            codigo varchar(30) PRIMARY KEY,
            categoria_id bigint NOT NULL REFERENCES catalogo(id) ON DELETE RESTRICT,
            texto text NOT NULL,
            orden smallint NOT NULL,
            activo boolean NOT NULL DEFAULT true
        );
        INSERT INTO pregunta_causa (codigo, categoria_id, texto, orden, activo)
        SELECT codigo, categoria_id, texto, orden, activo
          FROM configuracion WHERE registro_tipo = 'PREGUNTA_CAUSA';

        CREATE TABLE auditoria_administracion (
            id bigserial PRIMARY KEY,
            usuario_id bigint NOT NULL REFERENCES usuario(id) ON DELETE RESTRICT,
            fecha timestamptz NOT NULL,
            entidad varchar(100) NOT NULL,
            objeto varchar(100) NOT NULL,
            accion varchar(70) NOT NULL,
            antes jsonb NOT NULL DEFAULT '{}'::jsonb,
            despues jsonb NOT NULL DEFAULT '{}'::jsonb
        );
        CREATE INDEX auditoria_administracion_fecha_idx
            ON auditoria_administracion (fecha DESC);

        SELECT setval(pg_get_serial_sequence('catalogo','id'), GREATEST(COALESCE((SELECT MAX(id) FROM catalogo), 1), 1));
        SELECT setval(pg_get_serial_sequence('proceso','id'), GREATEST(COALESCE((SELECT MAX(id) FROM proceso), 1), 1));
        SELECT setval(pg_get_serial_sequence('subproceso','id'), GREATEST(COALESCE((SELECT MAX(id) FROM subproceso), 1), 1));
        SELECT setval(pg_get_serial_sequence('matriz_prioridad','id'), GREATEST(COALESCE((SELECT MAX(id) FROM matriz_prioridad), 1), 1));
        SELECT setval(pg_get_serial_sequence('configuracion_impacto','id'), GREATEST(COALESCE((SELECT MAX(id) FROM configuracion_impacto), 1), 1));
        SELECT setval(pg_get_serial_sequence('configuracion_urgencia','id'), GREATEST(COALESCE((SELECT MAX(id) FROM configuracion_urgencia), 1), 1));
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_delete_configuracionregistro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    state_operations = [
        migrations.RemoveConstraint(
            model_name='catalogo',
            name='catalogo_clase_valor_unico',
        ),
        migrations.RemoveConstraint(
            model_name='catalogo',
            name='catalogo_nivel_valido',
        ),
        migrations.RemoveConstraint(
            model_name='subproceso',
            name='subproceso_nombre_unico',
        ),
        migrations.RemoveField(
            model_name='configuracionurgencia',
            name='registro_tipo',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='validadores',
        ),
        migrations.AddField(
            model_name='proceso',
            name='validadores_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='auditoriaadministracion',
            name='accion',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='auditoriaadministracion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuracionimpacto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matrizprioridad',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preguntacausa',
            name='codigo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='subproceso',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='catalogo',
            constraint=models.UniqueConstraint(condition=models.Q(('valor__isnull', False)), fields=('clase', 'valor'), name='catalogo_clase_valor_unico'),
        ),
        migrations.AddConstraint(
            model_name='proceso',
            constraint=models.UniqueConstraint(fields=('nombre',), name='proceso_nombre_unico'),
        ),
        migrations.AddConstraint(
            model_name='subproceso',
            constraint=models.UniqueConstraint(fields=('proceso', 'nombre'), name='subproceso_proceso_nombre_unico'),
        ),
        migrations.AlterModelTable(
            name='auditoriaadministracion',
            table='auditoria_administracion',
        ),
        migrations.AlterModelTable(
            name='catalogo',
            table='catalogo',
        ),
        migrations.AlterModelTable(
            name='configuracionimpacto',
            table='configuracion_impacto',
        ),
        migrations.AlterModelTable(
            name='configuracionurgencia',
            table='configuracion_urgencia',
        ),
        migrations.AlterModelTable(
            name='matrizprioridad',
            table='matriz_prioridad',
        ),
        migrations.AlterModelTable(
            name='preguntacausa',
            table='pregunta_causa',
        ),
        migrations.AlterModelTable(
            name='proceso',
            table='proceso',
        ),
        migrations.AlterModelTable(
            name='subproceso',
            table='subproceso',
        ),
    ]
    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[migrations.RunPython(crear_tablas_normalizadas, migrations.RunPython.noop)],
        state_operations=state_operations,
    )]
