# Generated by Django 5.2.17 on 2026-10-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_remove_catalogo_catalogo_clase_valor_unico_and_more'),
        ('accounts', '0006_alter_usuario_table_alter_usuariorol_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditoriaadministracion',
            table='tbl_auditoria_administracion_nc',
        ),
        migrations.AlterModelTable(
            name='catalogo',
            table='tbl_catalogo_nc',
        ),
        migrations.AlterModelTable(
            name='configuracionimpacto',
            table='tbl_configuracion_impacto_nc',
        ),
        migrations.AlterModelTable(
            name='configuracionurgencia',
            table='tbl_configuracion_urgencia_nc',
        ),
        migrations.AlterModelTable(
            name='matrizprioridad',
            table='tbl_matriz_prioridad_nc',
        ),
        migrations.AlterModelTable(
            name='preguntacausa',
            table='tbl_pregunta_causa_nc',
        ),
        migrations.AlterModelTable(
            name='proceso',
            table='tbl_proceso_nc',
        ),
        migrations.AlterModelTable(
            name='procesovalidador',
            table='tbl_proceso_validador_nc',
        ),
        migrations.AlterModelTable(
            name='subproceso',
            table='tbl_subproceso_nc',
        ),
        migrations.RunSQL(
            sql=r"""
            CREATE OR REPLACE FUNCTION portal_sincronizar_proceso_validadores()
            RETURNS trigger AS $$
            BEGIN
              DELETE FROM tbl_proceso_validador_nc WHERE proceso_id = NEW.id;
              INSERT INTO tbl_proceso_validador_nc (proceso_id, usuario_id)
              SELECT NEW.id, valores.usuario_id::bigint
                FROM jsonb_array_elements_text(COALESCE(NEW.validadores_ids, '[]'::jsonb)) AS valores(usuario_id)
                JOIN tbl_usuario_nc u ON u.id = valores.usuario_id::bigint
              ON CONFLICT (proceso_id, usuario_id) DO NOTHING;
              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql=r"""
            CREATE OR REPLACE FUNCTION portal_sincronizar_proceso_validadores()
            RETURNS trigger AS $$
            BEGIN
              DELETE FROM proceso_validador WHERE proceso_id = NEW.id;
              INSERT INTO proceso_validador (proceso_id, usuario_id)
              SELECT NEW.id, valores.usuario_id::bigint
                FROM jsonb_array_elements_text(COALESCE(NEW.validadores_ids, '[]'::jsonb)) AS valores(usuario_id)
                JOIN usuario u ON u.id = valores.usuario_id::bigint
              ON CONFLICT (proceso_id, usuario_id) DO NOTHING;
              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
        ),
    ]
